/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventariox.genia.vista;


import java.awt.event.ActionEvent;
import javax.swing.Timer;

/**
 *
 * @author honey
 */
public class PantallaCarga extends javax.swing.JFrame {


    public PantallaCarga() {
        initComponents();
        lanzarBarraCarga();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPantCarga = new javax.swing.JPanel();
        barraProgreso = new javax.swing.JProgressBar();
        labelImagen = new javax.swing.JLabel();
        labelCargando = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        barraProgreso.setBackground(new java.awt.Color(102, 204, 255));
        barraProgreso.setForeground(new java.awt.Color(51, 51, 255));

        labelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventariox/genia/vista/circular_progress_indicator_square_small.gif"))); // NOI18N

        labelCargando.setText("Cargando....");

        javax.swing.GroupLayout panelPantCargaLayout = new javax.swing.GroupLayout(panelPantCarga);
        panelPantCarga.setLayout(panelPantCargaLayout);
        panelPantCargaLayout.setHorizontalGroup(
            panelPantCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPantCargaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPantCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barraProgreso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelPantCargaLayout.createSequentialGroup()
                        .addComponent(labelCargando, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 269, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelPantCargaLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(labelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPantCargaLayout.setVerticalGroup(
            panelPantCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPantCargaLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(labelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(barraProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelCargando)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPantCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPantCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //
    private void lanzarBarraCarga(){
        Timer tiempo = new Timer(2,(ActionEvent e)  ->{
            barraProgreso.setValue(barraProgreso.getValue()+1);
            barraProgreso.setStringPainted(true);
            barraProgreso.setString("Cargando..."+barraProgreso.getValue()+"%");
        });
        tiempo.start(   );
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgreso;
    private javax.swing.JLabel labelCargando;
    private javax.swing.JLabel labelImagen;
    private javax.swing.JPanel panelPantCarga;
    // End of variables declaration//GEN-END:variables
}
