/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventariox.genia.vista;

import inventariox.genia.ListaMedicamentos;
import inventariox.genia.MedicamentoRefrigerado;
import inventariox.genia.controladora.Controladora;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author honey
 */
public class PantallaEmpleado extends javax.swing.JFrame {
  Controladora c;

  /**
   * Creates new form PantallaEmpleado
   */
  public PantallaEmpleado(ListaMedicamentos lista) {
    c = new Controladora(lista);
    initComponents();
    c.ocultarOpcTipoMed(new JLabel[] { tabPanelModifLblCod, tabPanelModifLblFechaVence, tabPanelModifLblUnidDispo,
        tabPanelModifLblUnidVend, tabPanelModifLblCostoCompra, tabPanelModifLblNoAlma, tabPanelModifLblTempMax,
        tabPanelModifLblTempMin, tabPanelModifLblTiemNoRefri, tabPanelModifLblTiemAbr, tabPanelModifLblEjCod,
        tabPanelModifLblNomb, tabPanelModifLblEjFecha, tabPanelModifLblEjOfer, tabPanelModifLblEjNoAlma,
        tabPanelModifLblCelsius1, tabPanelModifLblCelsius2,tabPanelModifLblLote },
        new javax.swing.JTextField[] {
            tabPanelModifTxtCod,
            tabPanelModifTxtCostoCompra,
            tabPanelModifTxtFechaVence,
            tabPanelModifTxtNoAlma,
            tabPanelModifTxtNomb,
            tabPanelModifTxtOfer,
            tabPanelModifTxtTempMax,
            tabPanelModifTxtTempMin,
            tabPanelModifTxtTiemAbr,
            tabPanelModifTxtTiemNoRefri,
            tabPanelModifTxtUnidDispo,
            tabPanelModifTxtUnidVend,tabPanelModifTxtLote },
        new JButton[] { tabPanelModifBtnBorrar, tabPanelModifBtnRealizarCambios },
        tabPanelModifCmbVig, tabPanelModifRadBtnCadeFrio, tabPanelModifTogBtnAggOfer);
    // de Med Refrigerado
    c.ocultarOpcTipoMed(
        new JLabel[] { tabPanelAgLblTempMax, tabPanelAgLblTempMin, tabPanelAgLblTiemNoRefri, tabPanelAgLblTiemAbr,
            tabPanelModifLblTiemAbr,
            tabPanelAgLblCelsius1, tabPanelAgLblCelsius2 },
        new javax.swing.JTextField[] { tabPanelAgTxtTempMax,
            tabPanelAgTxtTempMin,
            tabPanelAgTxtTiemAbr,
            tabPanelAgTxtTiemNoRefri },
        tabPanelAgRadBtnCadeFrio);
    c.ocultarOpcMedNoRefri(tabPanelAgLblNoAlma, tabPanelAgTxtNoAlma, tabPanelAgLblEjNoAlma);

  }

  public JComboBox<String> getjComboBox1() {
    return jComboBox1;
  }

  public void setjComboBox1(JComboBox<String> jComboBox1) {
    this.jComboBox1 = jComboBox1;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabPanelAg = new javax.swing.JPanel();
        warningCod = new javax.swing.JLabel();
        warningNom = new javax.swing.JLabel();
        warningFecha = new javax.swing.JLabel();
        warningUnidDispo = new javax.swing.JLabel();
        warningCosto = new javax.swing.JLabel();
        warningOf = new javax.swing.JLabel();
        warningNoAlma = new javax.swing.JLabel();
        warningTempMax = new javax.swing.JLabel();
        warningTempMin = new javax.swing.JLabel();
        warningHorRefri = new javax.swing.JLabel();
        warningTiempAbrir = new javax.swing.JLabel();
        tabPanelAgCmbVig = new javax.swing.JComboBox<>();
        tabPanelAgTxtNomb = new javax.swing.JTextField();
        tabPanelAgLblCod = new javax.swing.JLabel();
        tabPanelAgTxtCod = new javax.swing.JTextField();
        tabPanelAgCmbTipMed = new javax.swing.JComboBox<>();
        tabPanelAgLblFechaVence = new javax.swing.JLabel();
        tabPanelAgTxtFechaVence = new javax.swing.JTextField();
        tabPanelAgLblUnidDispo = new javax.swing.JLabel();
        tabPanelAgTxtTempMax = new javax.swing.JTextField();
        tabPanelAgLblCostoCompra = new javax.swing.JLabel();
        tabPanelAgTxtCostoCompra = new javax.swing.JTextField();
        tabPanelAgTogBtnAggOfer = new javax.swing.JToggleButton();
        tabPanelAgLblNoAlma = new javax.swing.JLabel();
        tabPanelAgTxtNoAlma = new javax.swing.JTextField();
        tabPanelAgRadBtnCadeFrio = new javax.swing.JRadioButton();
        tabPanelAgLblTempMax = new javax.swing.JLabel();
        tabPanelAgTxtUnidDispo = new javax.swing.JTextField();
        tabPanelAgTxtTempMin = new javax.swing.JTextField();
        tabPanelAgLblTempMin = new javax.swing.JLabel();
        tabPanelAgLblTiemNoRefri = new javax.swing.JLabel();
        tabPanelAgTxtTiemNoRefri = new javax.swing.JTextField();
        tabPanelAgLblTiemAbr = new javax.swing.JLabel();
        tabPanelAgTxtTiemAbr = new javax.swing.JTextField();
        tabPanelAgTxtOfer = new javax.swing.JTextField();
        tabPanelAgLblEjCod = new javax.swing.JLabel();
        tabPanelAgLblNomb = new javax.swing.JLabel();
        tabPanelAgLblEjFecha = new javax.swing.JLabel();
        tabPanelAgLblEjOfer = new javax.swing.JLabel();
        tabPanelAgLblEjNoAlma = new javax.swing.JLabel();
        tabPanelAgLblCelsius1 = new javax.swing.JLabel();
        tabPanelAgLblCelsius2 = new javax.swing.JLabel();
        tabPanelAgBtnAgg = new javax.swing.JButton();
        tabPanelAgBtnBorrar = new javax.swing.JButton();
        warningLote = new javax.swing.JLabel();
        tabPanelAglblLote = new javax.swing.JLabel();
        tabPanelAgTxtLote = new javax.swing.JTextField();
        tabPanelAgIconoFondo = new javax.swing.JLabel();
        tabPanelModif = new javax.swing.JPanel();
        warningTiempAbrir1 = new javax.swing.JLabel();
        warningCod1 = new javax.swing.JLabel();
        warningUnidDispo1 = new javax.swing.JLabel();
        warningUnidVend = new javax.swing.JLabel();
        warningFecha1 = new javax.swing.JLabel();
        warningCosto1 = new javax.swing.JLabel();
        warningNom1 = new javax.swing.JLabel();
        warningTempMax1 = new javax.swing.JLabel();
        warningNoAlma1 = new javax.swing.JLabel();
        warningOf1 = new javax.swing.JLabel();
        warningHorRefri1 = new javax.swing.JLabel();
        warningTempMin1 = new javax.swing.JLabel();
        tabPanelModifBtnElim = new javax.swing.JButton();
        tabPanelModifBtnModif = new javax.swing.JButton();
        tabPanelModifCmbVig = new javax.swing.JComboBox<>();
        tabPanelModifTxtNomb = new javax.swing.JTextField();
        tabPanelModifLblCod = new javax.swing.JLabel();
        tabPanelModifTxtCod = new javax.swing.JTextField();
        tabPanelModifLblFechaVence = new javax.swing.JLabel();
        tabPanelModifTxtFechaVence = new javax.swing.JTextField();
        tabPanelModifLblUnidDispo = new javax.swing.JLabel();
        tabPanelModifTxtTempMax = new javax.swing.JTextField();
        tabPanelModifTxtUnidVend = new javax.swing.JTextField();
        tabPanelModifLblUnidVend = new javax.swing.JLabel();
        tabPanelModifLblCostoCompra = new javax.swing.JLabel();
        tabPanelModifTxtCostoCompra = new javax.swing.JTextField();
        tabPanelModifTogBtnAggOfer = new javax.swing.JToggleButton();
        tabPanelModifLblNoAlma = new javax.swing.JLabel();
        tabPanelModifTxtNoAlma = new javax.swing.JTextField();
        tabPanelModifRadBtnCadeFrio = new javax.swing.JRadioButton();
        tabPanelModifLblTempMax = new javax.swing.JLabel();
        tabPanelModifTxtUnidDispo = new javax.swing.JTextField();
        tabPanelModifTxtTempMin = new javax.swing.JTextField();
        tabPanelModifLblTempMin = new javax.swing.JLabel();
        tabPanelModifLblTiemNoRefri = new javax.swing.JLabel();
        tabPanelModifTxtTiemNoRefri = new javax.swing.JTextField();
        tabPanelModifLblTiemAbr = new javax.swing.JLabel();
        tabPanelModifTxtTiemAbr = new javax.swing.JTextField();
        tabPanelModifTxtOfer = new javax.swing.JTextField();
        tabPanelModifLblEjCod = new javax.swing.JLabel();
        tabPanelModifLblNomb = new javax.swing.JLabel();
        tabPanelModifLblEjFecha = new javax.swing.JLabel();
        tabPanelModifLblEjOfer = new javax.swing.JLabel();
        tabPanelModifLblEjNoAlma = new javax.swing.JLabel();
        tabPanelModifLblCelsius1 = new javax.swing.JLabel();
        tabPanelModifLblCelsius2 = new javax.swing.JLabel();
        tabPanelModifBtnRealizarCambios = new javax.swing.JButton();
        tabPanelModifBtnBorrar = new javax.swing.JButton();
        tabPanelModifLblLote = new javax.swing.JLabel();
        tabPanelModifTxtLote = new javax.swing.JTextField();
        warningLote1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/inventariox/genia/vista/pill.png")).getImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1 = new javax.swing.JButton();
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLayeredPane2.setLayer(jButton1, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventariox/genia/vista/antecedentes-medicos-limpios_53876-116873.png"))); // NOI18N
        jLayeredPane2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 600));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Source Code Pro", 0, 14)); // NOI18N
        jLabel2.setText("Seleccione un medicamento:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.setToolTipText("Selecciona el medicamento a modificar");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);
        c.mostrarInfo(jTextArea1, jComboBox1.getSelectedIndex());

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Source Code Pro", 0, 14)); // NOI18N
        jLabel4.setText("Cambios Realizados:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Agregar", tabPanelAg);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tabPanelAg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabPanelAg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        tabPanelAg.add(warningCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 40, 20));
        tabPanelAg.add(warningNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));
        tabPanelAg.add(warningFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));
        tabPanelAg.add(warningUnidDispo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));
        tabPanelAg.add(warningCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 30, 20));
        tabPanelAg.add(warningOf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 40, 20));
        tabPanelAg.add(warningNoAlma, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 30, 20));
        tabPanelAg.add(warningTempMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 30, 20));
        tabPanelAg.add(warningTempMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 30, 20));
        tabPanelAg.add(warningHorRefri, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 30, 30));
        tabPanelAg.add(warningTiempAbrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 30, 30));

        tabPanelAgCmbVig.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vigencia", "Disponible", "No disponible", "Retirado" }));
        tabPanelAg.add(tabPanelAgCmbVig, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 19, -1, -1));

        tabPanelAgTxtNomb.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelAgTxtNomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelAgTxtNombActionPerformed(evt);
            }
        });
        tabPanelAgTxtNomb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabPanelAgTxtNombKeyReleased(evt);
            }
        });
        tabPanelAg.add(tabPanelAgTxtNomb, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 97, 158, -1));

        tabPanelAgLblCod.setText("Ingrese el codigo del producto");
        tabPanelAg.add(tabPanelAgLblCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 22, -1, -1));

        tabPanelAgTxtCod.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelAgTxtCod.setName("Hola"); // NOI18N
        tabPanelAgTxtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelAgTxtCodActionPerformed(evt);
            }
        });
        tabPanelAgTxtCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabPanelAgTxtCodKeyReleased(evt);
            }
        });
        tabPanelAg.add(tabPanelAgTxtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 55, 158, -1));

        tabPanelAgCmbTipMed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de medicamento", "Refrigerado", "No Refrigerado" }));
        tabPanelAgCmbTipMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelAgCmbTipMedActionPerformed(evt);
            }
        });
        tabPanelAg.add(tabPanelAgCmbTipMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 55, -1, -1));

        tabPanelAgLblFechaVence.setText("Fecha Vencimiento");
        tabPanelAg.add(tabPanelAgLblFechaVence, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 139, -1, -1));

        tabPanelAgTxtFechaVence.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelAgTxtFechaVence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelAgTxtFechaVenceActionPerformed(evt);
            }
        });
        tabPanelAgTxtFechaVence.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabPanelAgTxtFechaVenceKeyReleased(evt);
            }
        });
        tabPanelAg.add(tabPanelAgTxtFechaVence, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 169, 100, -1));

        tabPanelAgLblUnidDispo.setText("Unidades Disponibles");
        tabPanelAg.add(tabPanelAgLblUnidDispo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 205, -1, -1));

        tabPanelAgTxtTempMax.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelAgTxtTempMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelAgTxtTempMaxActionPerformed(evt);
            }
        });
        tabPanelAgTxtTempMax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabPanelAgTxtTempMaxKeyReleased(evt);
            }
        });
        tabPanelAg.add(tabPanelAgTxtTempMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 169, 120, -1));

        tabPanelAgLblCostoCompra.setText("Costo de Compra");
        tabPanelAg.add(tabPanelAgLblCostoCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        tabPanelAgTxtCostoCompra.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelAgTxtCostoCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabPanelAgTxtCostoCompraKeyReleased(evt);
            }
        });
        tabPanelAg.add(tabPanelAgTxtCostoCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 136, -1));

        tabPanelAgTogBtnAggOfer.setText("Agregar Oferta");
        tabPanelAgTogBtnAggOfer.setVisible(true);
        tabPanelAgTogBtnAggOfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelAgTogBtnAggOferActionPerformed(evt);
            }
        });
        tabPanelAg.add(tabPanelAgTogBtnAggOfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        tabPanelAgLblNoAlma.setText("No almacenar en");
        tabPanelAg.add(tabPanelAgLblNoAlma, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        tabPanelAgTxtNoAlma.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelAgTxtNoAlma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelAgTxtNoAlmaActionPerformed(evt);
            }
        });
        tabPanelAgTxtNoAlma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabPanelAgTxtNoAlmaKeyReleased(evt);
            }
        });
        tabPanelAg.add(tabPanelAgTxtNoAlma, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 142, -1));

        tabPanelAgRadBtnCadeFrio.setText("Certificado de Cadena de Frio");
        tabPanelAgRadBtnCadeFrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelAgRadBtnCadeFrioActionPerformed(evt);
            }
        });
        tabPanelAg.add(tabPanelAgRadBtnCadeFrio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 98, -1, -1));

        tabPanelAgLblTempMax.setText("Temperatura MAX");
        tabPanelAg.add(tabPanelAgLblTempMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 139, -1, -1));

        tabPanelAgTxtUnidDispo.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelAgTxtUnidDispo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelAgTxtUnidDispoActionPerformed(evt);
            }
        });
        tabPanelAgTxtUnidDispo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabPanelAgTxtUnidDispoKeyReleased(evt);
            }
        });
        tabPanelAg.add(tabPanelAgTxtUnidDispo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 235, 136, -1));

        tabPanelAgTxtTempMin.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelAgTxtTempMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelAgTxtTempMinActionPerformed(evt);
            }
        });
        tabPanelAgTxtTempMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabPanelAgTxtTempMinKeyReleased(evt);
            }
        });
        tabPanelAg.add(tabPanelAgTxtTempMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 235, 120, -1));

        tabPanelAgLblTempMin.setText("Temperatura MIN");
        tabPanelAg.add(tabPanelAgLblTempMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 205, -1, -1));

        tabPanelAgLblTiemNoRefri.setText("Horas sin refrigeracion");
        tabPanelAg.add(tabPanelAgLblTiemNoRefri, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 271, -1, -1));

        tabPanelAgTxtTiemNoRefri.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelAgTxtTiemNoRefri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelAgTxtTiemNoRefriActionPerformed(evt);
            }
        });
        tabPanelAgTxtTiemNoRefri.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabPanelAgTxtTiemNoRefriKeyReleased(evt);
            }
        });
        tabPanelAg.add(tabPanelAgTxtTiemNoRefri, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 295, 165, -1));

        tabPanelAgLblTiemAbr.setText("Duracion despues de abrirlo");
        tabPanelAg.add(tabPanelAgLblTiemAbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 325, -1, -1));

        tabPanelAgTxtTiemAbr.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelAgTxtTiemAbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelAgTxtTiemAbrActionPerformed(evt);
            }
        });
        tabPanelAgTxtTiemAbr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabPanelAgTxtTiemAbrKeyReleased(evt);
            }
        });
        tabPanelAg.add(tabPanelAgTxtTiemAbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 355, 171, -1));

        tabPanelAgTxtOfer.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelAgTxtOfer.setVisible(false);
        tabPanelAgTxtOfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelAgTxtOferActionPerformed(evt);
            }
        });
        tabPanelAgTxtOfer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabPanelAgTxtOferKeyReleased(evt);
            }
        });
        tabPanelAg.add(tabPanelAgTxtOfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 142, -1));

        tabPanelAgLblEjCod.setText("Ej: AA12345678");
        tabPanelAg.add(tabPanelAgLblEjCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 58, -1, -1));

        tabPanelAgLblNomb.setText("Nombre");
        tabPanelAg.add(tabPanelAgLblNomb, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        tabPanelAgLblEjFecha.setText("MM/AAAA");
        tabPanelAg.add(tabPanelAgLblEjFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 172, -1, -1));

        tabPanelAgLblEjOfer.setText("Escriba el porcentaje (sin %)");
        tabPanelAgLblEjOfer.setVisible(false);
        tabPanelAg.add(tabPanelAgLblEjOfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        tabPanelAgLblEjNoAlma.setText("Separar con comas");
        tabPanelAgLblEjNoAlma.setVisible(false);
        tabPanelAg.add(tabPanelAgLblEjNoAlma, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, -1, -1));

        tabPanelAgLblCelsius1.setText("Celsius");
        tabPanelAg.add(tabPanelAgLblCelsius1, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 172, -1, -1));

        tabPanelAgLblCelsius2.setText("Celsius");
        tabPanelAg.add(tabPanelAgLblCelsius2, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 238, -1, -1));

        tabPanelAgBtnAgg.setForeground(new java.awt.Color(0, 153, 51));
        tabPanelAgBtnAgg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventariox/genia/vista/anadir.png"))); // NOI18N
        tabPanelAgBtnAgg.setText("AGREGAR");
        tabPanelAgBtnAgg.setToolTipText("Lo agrega al inventario");
        tabPanelAgBtnAgg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelAgBtnAggActionPerformed(evt);
            }
        });
        tabPanelAg.add(tabPanelAgBtnAgg, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 397, -1, -1));

        tabPanelAgBtnBorrar.setForeground(new java.awt.Color(255, 0, 51));
        tabPanelAgBtnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventariox/genia/vista/escoba.png"))); // NOI18N
        tabPanelAgBtnBorrar.setText("LIMPIAR");
        tabPanelAgBtnBorrar.setToolTipText("Borra los datos ingresados (no el producto)");
        tabPanelAgBtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelAgBtnBorrarActionPerformed(evt);
            }
        });
        tabPanelAg.add(tabPanelAgBtnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 397, -1, -1));
        tabPanelAg.add(warningLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 50, 30));

        tabPanelAglblLote.setText("Ingrese el numero de lote");
        tabPanelAg.add(tabPanelAglblLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        tabPanelAgTxtLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelAgTxtLoteActionPerformed(evt);
            }
        });
        tabPanelAgTxtLote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabPanelAgTxtLoteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabPanelAgTxtLoteKeyReleased(evt);
            }
        });
        tabPanelAg.add(tabPanelAgTxtLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 140, -1));

        tabPanelAgIconoFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventariox/genia/vista/simbolo-de-la-medicina (1).png"))); // NOI18N
        tabPanelAg.add(tabPanelAgIconoFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jTabbedPane1.addTab("Agregar", new javax.swing.ImageIcon(getClass().getResource("/inventariox/genia/vista/agregar.png")), tabPanelAg, "Agrega un medicamento al inventario"); // NOI18N

        tabPanelModif.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabPanelModif.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        tabPanelModif.add(warningTiempAbrir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 30, 30));
        tabPanelModif.add(warningCod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 40, 20));
        tabPanelModif.add(warningUnidDispo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 30, 30));
        tabPanelModif.add(warningUnidVend, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 30, 20));
        tabPanelModif.add(warningFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 40, 30));
        tabPanelModif.add(warningCosto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 40, 20));
        tabPanelModif.add(warningNom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 30, 20));
        tabPanelModif.add(warningTempMax1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 30, 20));
        tabPanelModif.add(warningNoAlma1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 30, 20));
        tabPanelModif.add(warningOf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 40, 20));
        tabPanelModif.add(warningHorRefri1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 30, 30));
        tabPanelModif.add(warningTempMin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 30, 20));

        tabPanelModifBtnElim.setForeground(new java.awt.Color(255, 0, 51));
        tabPanelModifBtnElim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventariox/genia/vista/cancelar.png"))); // NOI18N
        tabPanelModifBtnElim.setText("ELMINAR PRODUCTO");
        tabPanelModifBtnElim.setToolTipText("Elimina el medicamento seleccionado");
        tabPanelModifBtnElim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabPanelModifBtnElim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelModifBtnElimActionPerformed(evt);
            }
        });
        tabPanelModif.add(tabPanelModifBtnElim, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        tabPanelModifBtnModif.setForeground(new java.awt.Color(102, 204, 0));
        tabPanelModifBtnModif.setText("MODIFICAR PRODUCTO");
        tabPanelModifBtnModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelModifBtnModifActionPerformed(evt);
            }
        });
        tabPanelModif.add(tabPanelModifBtnModif, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));

        tabPanelModifCmbVig.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vigencia", "Disponible", "No disponible", "Retirado" }));
        tabPanelModifCmbVig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelModifCmbVigActionPerformed(evt);
            }
        });
        tabPanelModif.add(tabPanelModifCmbVig, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        tabPanelModifTxtNomb.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelModifTxtNomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelModifTxtNombActionPerformed(evt);
            }
        });
        tabPanelModifTxtNomb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabPanelModifTxtNombKeyReleased(evt);
            }
        });
        tabPanelModif.add(tabPanelModifTxtNomb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 158, -1));

        tabPanelModifLblCod.setText("Ingrese el codigo del producto");
        tabPanelModif.add(tabPanelModifLblCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        tabPanelModifTxtCod.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelModifTxtCod.setName("Hola"); // NOI18N
        tabPanelModifTxtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelModifTxtCodActionPerformed(evt);
            }
        });
        tabPanelModifTxtCod.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tabPanelModifTxtCodPropertyChange(evt);
            }
        });
        tabPanelModifTxtCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabPanelModifTxtCodKeyReleased(evt);
            }
        });
        tabPanelModif.add(tabPanelModifTxtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 158, -1));

        tabPanelModifLblFechaVence.setText("Fecha Vencimiento");
        tabPanelModif.add(tabPanelModifLblFechaVence, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        tabPanelModifTxtFechaVence.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelModifTxtFechaVence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelModifTxtFechaVenceActionPerformed(evt);
            }
        });
        tabPanelModifTxtFechaVence.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabPanelModifTxtFechaVenceKeyReleased(evt);
            }
        });
        tabPanelModif.add(tabPanelModifTxtFechaVence, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 100, -1));

        tabPanelModifLblUnidDispo.setText("Unidades Disponibles");
        tabPanelModif.add(tabPanelModifLblUnidDispo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        tabPanelModifTxtTempMax.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelModifTxtTempMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelModifTxtTempMaxActionPerformed(evt);
            }
        });
        tabPanelModifTxtTempMax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabPanelModifTxtTempMaxKeyReleased(evt);
            }
        });
        tabPanelModif.add(tabPanelModifTxtTempMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 120, -1));

        tabPanelModifTxtUnidVend.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelModifTxtUnidVend.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabPanelModifTxtUnidVendKeyReleased(evt);
            }
        });
        tabPanelModif.add(tabPanelModifTxtUnidVend, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 136, -1));

        tabPanelModifLblUnidVend.setText("Unidades Vendidas");
        tabPanelModif.add(tabPanelModifLblUnidVend, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        tabPanelModifLblCostoCompra.setText("Costo de Compra");
        tabPanelModif.add(tabPanelModifLblCostoCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        tabPanelModifTxtCostoCompra.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelModifTxtCostoCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabPanelModifTxtCostoCompraKeyReleased(evt);
            }
        });
        tabPanelModif.add(tabPanelModifTxtCostoCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 136, -1));

        tabPanelModifTogBtnAggOfer.setText("Agregar Oferta");
        tabPanelModifTogBtnAggOfer.setVisible(false);
        tabPanelModifTogBtnAggOfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelModifTogBtnAggOferActionPerformed(evt);
            }
        });
        tabPanelModif.add(tabPanelModifTogBtnAggOfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        tabPanelModifLblNoAlma.setText("No almacenar en");
        tabPanelModifLblNoAlma.setVisible(false);
        tabPanelModif.add(tabPanelModifLblNoAlma, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, -1));

        tabPanelModifTxtNoAlma.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelModifTxtNoAlma.setVisible(false);
        tabPanelModifTxtNoAlma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelModifTxtNoAlmaActionPerformed(evt);
            }
        });
        tabPanelModifTxtNoAlma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabPanelModifTxtNoAlmaKeyReleased(evt);
            }
        });
        tabPanelModif.add(tabPanelModifTxtNoAlma, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 142, -1));

        tabPanelModifRadBtnCadeFrio.setVisible(false);
        tabPanelModifRadBtnCadeFrio.setText("Certificado de Cadena de Frio");
        tabPanelModifRadBtnCadeFrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelModifRadBtnCadeFrioActionPerformed(evt);
            }
        });
        tabPanelModif.add(tabPanelModifRadBtnCadeFrio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));

        tabPanelModifLblTempMax.setText("Temperatura MAX");
        tabPanelModif.add(tabPanelModifLblTempMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        tabPanelModifTxtUnidDispo.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelModifTxtUnidDispo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelModifTxtUnidDispoActionPerformed(evt);
            }
        });
        tabPanelModifTxtUnidDispo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabPanelModifTxtUnidDispoKeyReleased(evt);
            }
        });
        tabPanelModif.add(tabPanelModifTxtUnidDispo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 136, -1));

        tabPanelModifTxtTempMin.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelModifTxtTempMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelModifTxtTempMinActionPerformed(evt);
            }
        });
        tabPanelModifTxtTempMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabPanelModifTxtTempMinKeyReleased(evt);
            }
        });
        tabPanelModif.add(tabPanelModifTxtTempMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 120, -1));

        tabPanelModifLblTempMin.setText("Temperatura MIN");
        tabPanelModif.add(tabPanelModifLblTempMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        tabPanelModifLblTiemNoRefri.setText("Horas sin refrigeracion");
        tabPanelModif.add(tabPanelModifLblTiemNoRefri, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        tabPanelModifTxtTiemNoRefri.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelModifTxtTiemNoRefri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelModifTxtTiemNoRefriActionPerformed(evt);
            }
        });
        tabPanelModifTxtTiemNoRefri.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabPanelModifTxtTiemNoRefriKeyReleased(evt);
            }
        });
        tabPanelModif.add(tabPanelModifTxtTiemNoRefri, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 165, -1));

        tabPanelModifLblTiemAbr.setText("Duracion despues de abrirlo");
        tabPanelModif.add(tabPanelModifLblTiemAbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, -1));

        tabPanelModifTxtTiemAbr.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelModifTxtTiemAbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelModifTxtTiemAbrActionPerformed(evt);
            }
        });
        tabPanelModifTxtTiemAbr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabPanelModifTxtTiemAbrKeyReleased(evt);
            }
        });
        tabPanelModif.add(tabPanelModifTxtTiemAbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 171, -1));

        tabPanelModifTxtOfer.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelModifTxtOfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelModifTxtOferActionPerformed(evt);
            }
        });
        tabPanelModifTxtOfer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabPanelModifTxtOferKeyReleased(evt);
            }
        });
        tabPanelModif.add(tabPanelModifTxtOfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 142, -1));

        tabPanelModifLblEjCod.setText("Ej: AA12345678");
        tabPanelModif.add(tabPanelModifLblEjCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        tabPanelModifLblNomb.setText("Nombre");
        tabPanelModif.add(tabPanelModifLblNomb, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        tabPanelModifLblEjFecha.setText("MM/AAAA");
        tabPanelModif.add(tabPanelModifLblEjFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        tabPanelModifLblEjOfer.setText("Escriba el porcentaje (sin %)");
        tabPanelModif.add(tabPanelModifLblEjOfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, -1, -1));

        tabPanelModifLblEjNoAlma.setText("Separar con comas");
        tabPanelModifLblEjNoAlma.setVisible(false);
        tabPanelModif.add(tabPanelModifLblEjNoAlma, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, -1, -1));

        tabPanelModifLblCelsius1.setText("Celsius");
        tabPanelModif.add(tabPanelModifLblCelsius1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        tabPanelModifLblCelsius2.setText("Celsius");
        tabPanelModif.add(tabPanelModifLblCelsius2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, -1));

        tabPanelModifBtnRealizarCambios.setForeground(new java.awt.Color(0, 153, 51));
        tabPanelModifBtnRealizarCambios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventariox/genia/vista/anadir.png"))); // NOI18N
        tabPanelModifBtnRealizarCambios.setText("REALIZAR CAMBIOS");
        tabPanelModifBtnRealizarCambios.setToolTipText("Agregar Cambios");
        tabPanelModifBtnRealizarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelModifBtnRealizarCambiosActionPerformed(evt);
            }
        });
        tabPanelModif.add(tabPanelModifBtnRealizarCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, -1, -1));

        tabPanelModifBtnBorrar.setForeground(new java.awt.Color(255, 0, 51));
        tabPanelModifBtnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventariox/genia/vista/escoba.png"))); // NOI18N
        tabPanelModifBtnBorrar.setText("LIMPIAR");
        tabPanelModifBtnBorrar.setToolTipText("Borra los datos ingresados (no el producto)");
        tabPanelModifBtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelModifBtnBorrarActionPerformed(evt);
            }
        });
        tabPanelModif.add(tabPanelModifBtnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, -1, -1));

        tabPanelModifLblLote.setText("Lote");
        tabPanelModif.add(tabPanelModifLblLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        tabPanelModifTxtLote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabPanelModifTxtLoteKeyReleased(evt);
            }
        });
        tabPanelModif.add(tabPanelModifTxtLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 130, -1));
        tabPanelModif.add(warningLote1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 40, 30));

        jTabbedPane1.addTab("Modificar", new javax.swing.ImageIcon(getClass().getResource("/inventariox/genia/vista/lista.png")), tabPanelModif, "Modificar el medicamento seleccionado"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        jLayeredPane1.setLayer(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabPanelModifTxtLoteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabPanelModifTxtLoteKeyReleased
        // TODO add your handling code here:
        c.validarNatural(tabPanelModifTxtLote.getText(),warningLote1);
    }//GEN-LAST:event_tabPanelModifTxtLoteKeyReleased

    private void tabPanelModifBtnRealizarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabPanelModifBtnRealizarCambiosActionPerformed
        // TODO add your handling code here:
        c.realizarCambios(
                tabPanelModifTxtCod.getText(), 
                tabPanelModifTxtNomb.getText(), 
                tabPanelModifTxtFechaVence.getText(),
        tabPanelModifTxtCostoCompra.getText(),
        tabPanelModifTxtLote.getText(),
        tabPanelModifTxtUnidDispo.getText(), tabPanelModifTxtUnidVend.getText(),
        tabPanelModifTogBtnAggOfer.isSelected(),
        tabPanelModifTxtOfer.getText(), 
        tabPanelModifCmbVig.getSelectedIndex(),
        tabPanelModifRadBtnCadeFrio.isSelected(), 
        tabPanelModifTxtTempMax.getText(), 
        tabPanelModifTxtTempMin.getText(),
        tabPanelModifTxtTiemNoRefri.getText(), 
        tabPanelModifTxtTiemAbr.getText(), 
        tabPanelModifTxtNoAlma.getText(),
        jTextArea2,
        jComboBox1.getSelectedIndex());
        c.agregarNombMed(jComboBox1);
        c.mostrarInfo(jTextArea1, jComboBox1.getSelectedIndex());
        
        c.ocultarOpcTipoMed(new JLabel[] { tabPanelModifLblCod, tabPanelModifLblFechaVence, tabPanelModifLblUnidDispo,
        tabPanelModifLblUnidVend, tabPanelModifLblCostoCompra, tabPanelModifLblNoAlma, tabPanelModifLblTempMax,
        tabPanelModifLblTempMin, tabPanelModifLblTiemNoRefri, tabPanelModifLblTiemAbr, tabPanelModifLblEjCod,
        tabPanelModifLblNomb, tabPanelModifLblEjFecha, tabPanelModifLblEjOfer, tabPanelModifLblEjNoAlma,
        tabPanelModifLblCelsius1, tabPanelModifLblCelsius2, tabPanelModifLblLote },
        new javax.swing.JTextField[] {
            tabPanelModifTxtCod,
            tabPanelModifTxtCostoCompra,
            tabPanelModifTxtFechaVence,
            tabPanelModifTxtNoAlma,
            tabPanelModifTxtNomb,
            tabPanelModifTxtOfer,
            tabPanelModifTxtTempMax,
            tabPanelModifTxtTempMin,
            tabPanelModifTxtTiemAbr,
            tabPanelModifTxtTiemNoRefri,
            tabPanelModifTxtUnidDispo,
            tabPanelModifTxtUnidVend,
            tabPanelModifTxtLote},
        new JButton[] { tabPanelModifBtnBorrar, tabPanelModifBtnRealizarCambios },
        tabPanelModifCmbVig, tabPanelModifRadBtnCadeFrio, tabPanelModifTogBtnAggOfer);
    
    c.ocultarIcon(new JLabel[] {
        warningCod1,
        warningNom1,
        warningFecha1,
        warningUnidDispo1,
        warningCosto1,
        warningOf1,
        warningNoAlma1,
        warningTempMax1,
        warningTempMin1,
        warningHorRefri1,
        warningTiempAbrir1,
        warningLote1,
        warningUnidVend
    });
    
    }//GEN-LAST:event_tabPanelModifBtnRealizarCambiosActionPerformed

  private void tabPanelModifBtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelModifBtnBorrarActionPerformed
    // TODO add your handling code here:
    c.limpiar(new JTextField[] {
        tabPanelModifTxtCod,
        tabPanelModifTxtCostoCompra,
        tabPanelModifTxtFechaVence,
        tabPanelModifTxtNoAlma,
        tabPanelModifTxtNomb,
        tabPanelModifTxtOfer,
        tabPanelModifTxtTempMax,
        tabPanelModifTxtTempMin,
        tabPanelModifTxtTiemAbr,
        tabPanelModifTxtTiemNoRefri,
        tabPanelModifTxtUnidDispo, tabPanelModifTxtUnidVend,
        tabPanelModifTxtLote

    }, tabPanelModifCmbVig, tabPanelModifRadBtnCadeFrio);
    c.ocultarIcon(new JLabel[] {
        warningCod1,
        warningNom1,
        warningFecha1,
        warningUnidDispo1,warningUnidVend,
        warningCosto1,
        warningOf1,
        warningNoAlma1,
        warningTempMax1,
        warningTempMin1,
        warningHorRefri1,
        warningTiempAbrir1,
        warningLote1
    });

  }// GEN-LAST:event_tabPanelModifBtnBorrarActionPerformed
   // TODO add your handling code here:
   // TODO add your handling code here:
   // TODO add your handling code here:

  private void tabPanelModifTxtOferActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelModifTxtOferActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifTxtOferActionPerformed

  private void tabPanelModifTxtTiemAbrActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelModifTxtTiemAbrActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifTxtTiemAbrActionPerformed

  private void tabPanelModifTxtTiemNoRefriActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelModifTxtTiemNoRefriActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifTxtTiemNoRefriActionPerformed

  private void tabPanelModifTxtTempMinActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelModifTxtTempMinActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifTxtTempMinActionPerformed

  private void tabPanelModifTxtUnidDispoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelModifTxtUnidDispoActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifTxtUnidDispoActionPerformed
   // TODO add your handling code here:
   // TODO add your handling code here:
   // TODO add your handling code here:

  private void tabPanelModifRadBtnCadeFrioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelModifRadBtnCadeFrioActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifRadBtnCadeFrioActionPerformed

  private void tabPanelModifTxtNoAlmaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelModifTxtNoAlmaActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifTxtNoAlmaActionPerformed
   // TODO add your handling code here:
   // TODO add your handling code here:

  private void tabPanelModifTogBtnAggOferActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelModifTogBtnAggOferActionPerformed
    // TODO add your handling code here:
    if (tabPanelModifTogBtnAggOfer.isSelected()) {
      c.mostrarOferta(tabPanelModifTxtOfer, tabPanelModifLblEjOfer);
    } else
      c.ocultarOferta(tabPanelModifTxtOfer, tabPanelModifLblEjOfer);
  }// GEN-LAST:event_tabPanelModifTogBtnAggOferActionPerformed

  private void tabPanelModifTxtTempMaxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelModifTxtTempMaxActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifTxtTempMaxActionPerformed

  private void tabPanelModifTxtFechaVenceActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelModifTxtFechaVenceActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifTxtFechaVenceActionPerformed

  private void tabPanelModifTxtCodPropertyChange(java.beans.PropertyChangeEvent evt) {// GEN-FIRST:event_tabPanelModifTxtCodPropertyChange
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifTxtCodPropertyChange

  private void tabPanelModifTxtCodActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelModifTxtCodActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifTxtCodActionPerformed

  private void tabPanelModifTxtNombActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelModifTxtNombActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifTxtNombActionPerformed

  private void tabPanelModifCmbVigActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelModifCmbVigActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifCmbVigActionPerformed

  private void tabPanelModifBtnModifActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelModifBtnModifActionPerformed
    // TODO add your handling code here:
    c.mostrarOpcModif(new JButton[] { tabPanelModifBtnBorrar, tabPanelModifBtnRealizarCambios }, new JLabel[] {
        tabPanelModifLblCod, tabPanelModifLblFechaVence, tabPanelModifLblUnidDispo,
        tabPanelModifLblUnidVend, tabPanelModifLblCostoCompra, tabPanelModifLblEjCod,
        tabPanelModifLblNomb, tabPanelModifLblEjFecha, tabPanelModifLblLote

    }, new JTextField[] {
        tabPanelModifTxtCod,
        tabPanelModifTxtCostoCompra,
        tabPanelModifTxtFechaVence,

        tabPanelModifTxtNomb,

        tabPanelModifTxtUnidDispo,
        tabPanelModifTxtUnidVend,
        tabPanelModifTxtLote
    }, tabPanelModifTogBtnAggOfer, tabPanelModifCmbVig);
    if (c.medNecesitaRefrigeracion(jComboBox1.getSelectedIndex())) {
      c.ocultarOpcMedNoRefri(tabPanelModifLblNoAlma, tabPanelModifTxtNoAlma, tabPanelModifLblEjNoAlma);
      c.mostrarTipoMedRefri(
          new JLabel[] { tabPanelModifLblTempMax, tabPanelModifLblTempMin, tabPanelModifLblTiemNoRefri,
              tabPanelModifLblTiemAbr, tabPanelModifLblCelsius1, tabPanelModifLblCelsius2 },
          new JTextField[] { tabPanelModifTxtTempMax, tabPanelModifTxtTempMin, tabPanelModifTxtTiemAbr,
              tabPanelModifTxtTiemNoRefri },
          tabPanelModifRadBtnCadeFrio);
    } else {
      c.ocultarOpcMedRefri(new JLabel[] {
          tabPanelModifLblTempMax,
          tabPanelModifLblTempMin, tabPanelModifLblTiemNoRefri, tabPanelModifLblTiemAbr,
          tabPanelModifLblCelsius1, tabPanelModifLblCelsius2
      }, new JTextField[] {
          tabPanelModifTxtTempMax,
          tabPanelModifTxtTempMin,
          tabPanelModifTxtTiemAbr,
          tabPanelModifTxtTiemNoRefri
      }, tabPanelModifRadBtnCadeFrio);
      c.mostrarOpcMedNoRefri(tabPanelModifLblNoAlma, tabPanelModifTxtNoAlma, tabPanelModifLblEjNoAlma);
    }

  }// GEN-LAST:event_tabPanelModifBtnModifActionPerformed

  private void tabPanelModifBtnElimActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelModifBtnElimActionPerformed
    // TODO add your handling code here:
    c.borrarSeleccionado(jComboBox1.getSelectedIndex());
    c.agregarNombMed(jComboBox1);
    c.mostrarInfo(jTextArea1, jComboBox1.getSelectedIndex());
  }// GEN-LAST:event_tabPanelModifBtnElimActionPerformed

  private void tabPanelAgTxtCostoCompraKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tabPanelAgTxtCostoCompraKeyReleased
    // TODO add your handling code here:
    c.validarCosto(tabPanelAgTxtCostoCompra.getText(), warningCosto);
  }// GEN-LAST:event_tabPanelAgTxtCostoCompraKeyReleased

  private void tabPanelModifTxtCodKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tabPanelModifTxtCodKeyReleased
    // TODO add your handling code here:
    c.validarCodigoMed(tabPanelModifTxtCod.getText(), warningCod1);

  }// GEN-LAST:event_tabPanelModifTxtCodKeyReleased

  private void tabPanelModifTxtNombKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tabPanelModifTxtNombKeyReleased
    // TODO add your handling code here:
    c.validarNombre(tabPanelModifTxtNomb.getText(), warningNom1);

  }// GEN-LAST:event_tabPanelModifTxtNombKeyReleased

  private void tabPanelModifTxtFechaVenceKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tabPanelModifTxtFechaVenceKeyReleased
    // TODO add your handling code here:
    c.validarFecha(tabPanelModifTxtFechaVence.getText(), warningFecha1);
  }// GEN-LAST:event_tabPanelModifTxtFechaVenceKeyReleased

  private void tabPanelModifTxtUnidDispoKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tabPanelModifTxtUnidDispoKeyReleased
    // TODO add your handling code here:
    c.validarNatural(tabPanelModifTxtUnidDispo.getText(), warningUnidDispo1);
  }// GEN-LAST:event_tabPanelModifTxtUnidDispoKeyReleased

  private void tabPanelModifTxtUnidVendKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tabPanelModifTxtUnidVendKeyReleased
    // TODO add your handling code here:
    c.validarNatural(tabPanelModifTxtUnidVend.getText(), warningUnidVend);

  }// GEN-LAST:event_tabPanelModifTxtUnidVendKeyReleased

  private void tabPanelModifTxtCostoCompraKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tabPanelModifTxtCostoCompraKeyReleased
    // TODO add your handling code here:
    c.validarCosto(tabPanelModifTxtCostoCompra.getText(), warningCosto1);
  }// GEN-LAST:event_tabPanelModifTxtCostoCompraKeyReleased

  private void tabPanelModifTxtOferKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tabPanelModifTxtOferKeyReleased
    // TODO add your handling code here:
    c.validarOferta(tabPanelModifTxtOfer.getText(), warningOf1);
  }// GEN-LAST:event_tabPanelModifTxtOferKeyReleased

  private void tabPanelModifTxtNoAlmaKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tabPanelModifTxtNoAlmaKeyReleased
    // TODO add your handling code here:
    c.validarNoAlma(tabPanelModifTxtNoAlma.getText(), warningNoAlma1);
  }// GEN-LAST:event_tabPanelModifTxtNoAlmaKeyReleased

  private void tabPanelModifTxtTempMaxKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tabPanelModifTxtTempMaxKeyReleased
    // TODO add your handling code here:
    c.validarTemp(tabPanelModifTxtTempMax.getText(), tabPanelModifTxtTempMin.getText(), warningTempMax1);
  }// GEN-LAST:event_tabPanelModifTxtTempMaxKeyReleased

  private void tabPanelModifTxtTempMinKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tabPanelModifTxtTempMinKeyReleased
    // TODO add your handling code here:
    c.validarTemp(tabPanelModifTxtTempMax.getText(), tabPanelModifTxtTempMin.getText(), warningTempMin1);
  }// GEN-LAST:event_tabPanelModifTxtTempMinKeyReleased

  private void tabPanelModifTxtTiemNoRefriKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tabPanelModifTxtTiemNoRefriKeyReleased
    // TODO add your handling code here:
    c.validarHoras(tabPanelModifTxtTiemNoRefri.getText(), warningHorRefri1);
  }// GEN-LAST:event_tabPanelModifTxtTiemNoRefriKeyReleased

  private void tabPanelModifTxtTiemAbrKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tabPanelModifTxtTiemAbrKeyReleased
    // TODO add your handling code here:
    c.validarHoras(tabPanelModifTxtTiemAbr.getText(), warningTiempAbrir1);
  }// GEN-LAST:event_tabPanelModifTxtTiemAbrKeyReleased

  private void tabPanelAgBtnAggActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelAgBtnAggActionPerformed
    // TODO add your handling code here:
    if (!c.agregarMed(tabPanelAgTxtCod.getText(), tabPanelAgTxtNomb.getText(), tabPanelAgTxtFechaVence.getText(),
        tabPanelAgTxtCostoCompra.getText(),
        tabPanelAgTxtLote.getText() , tabPanelAgTxtUnidDispo.getText(), tabPanelAgTogBtnAggOfer.isSelected(),
        tabPanelAgTxtOfer.getText(), tabPanelAgCmbVig.getSelectedIndex(), tabPanelAgCmbTipMed.getSelectedIndex(),
        tabPanelAgRadBtnCadeFrio.isSelected(), tabPanelAgTxtTempMax.getText(), tabPanelAgTxtTempMin.getText(),
        tabPanelAgTxtTiemNoRefri.getText(), tabPanelAgTxtTiemAbr.getText(), tabPanelAgTxtNoAlma.getText()))
      return;
    c.agregarNombMed(jComboBox1);
    c.mostrarInfo(jTextArea1, jComboBox1.getSelectedIndex());
    c.ocultarIcon(new JLabel[] {
        warningCod,
        warningNom,
        warningFecha,
        warningUnidDispo,
        warningCosto,
        warningOf,
        warningNoAlma,
        warningTempMax,
        warningTempMin,
        warningHorRefri,
        warningTiempAbrir,
        warningLote
    });
    c.limpiar(new JTextField[] {
        tabPanelAgTxtCod,
        tabPanelAgTxtCostoCompra,
        tabPanelAgTxtFechaVence,
        tabPanelAgTxtNoAlma,
        tabPanelAgTxtNomb,
        tabPanelAgTxtOfer,
        tabPanelAgTxtTempMax,
        tabPanelAgTxtTempMin,
        tabPanelAgTxtTiemAbr,
        tabPanelAgTxtTiemNoRefri,
        tabPanelAgTxtUnidDispo,
        tabPanelAgTxtLote
    }, tabPanelAgCmbVig, tabPanelAgCmbTipMed, tabPanelAgRadBtnCadeFrio);
  }// GEN-LAST:event_tabPanelAgBtnAggActionPerformed

  private void tabPanelAgTxtLoteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelAgTxtLoteActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelAgTxtLoteActionPerformed

  private void tabPanelAgTxtLoteKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tabPanelAgTxtLoteKeyPressed
    // TODO add your handling code here:

  }// GEN-LAST:event_tabPanelAgTxtLoteKeyPressed

  private void tabPanelAgTxtLoteKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tabPanelAgTxtLoteKeyReleased
    // TODO add your handling code here:
    c.validarNatural(tabPanelAgTxtLote.getText(), warningLote);
  }// GEN-LAST:event_tabPanelAgTxtLoteKeyReleased

  private void tabPanelModifBtnModifActionPerformed() {// GEN-FIRST:event_tabPanelModifBtnModifActionPerformed
    // TODO add your handling code here:
    c.mostrarOpcModif(new JButton[] { tabPanelModifBtnRealizarCambios, tabPanelModifBtnBorrar },
        new JLabel[] { tabPanelModifLblCod, tabPanelModifLblFechaVence, tabPanelModifLblUnidDispo,
            tabPanelModifLblUnidVend, tabPanelModifLblCostoCompra, tabPanelModifLblEjCod,
            tabPanelModifLblNomb, tabPanelModifLblEjFecha },
        new JTextField[] { tabPanelModifTxtCod,
            tabPanelModifTxtCostoCompra,
            tabPanelModifTxtFechaVence,
            tabPanelModifTxtNomb, tabPanelModifTxtUnidDispo,
            tabPanelModifTxtUnidVend },
        tabPanelModifTogBtnAggOfer, tabPanelModifCmbVig);

    if (c.medNecesitaRefrigeracion(jComboBox1.getSelectedIndex())) {
      c.mostrarOpcMedRefri(new JLabel[] { tabPanelModifLblTempMax,
          tabPanelModifLblTempMin, tabPanelModifLblTiemNoRefri, tabPanelModifLblTiemAbr, // tabPanelModifLblEjOfer,
          tabPanelModifLblCelsius1, tabPanelModifLblCelsius2 },
          new javax.swing.JTextField[] {
              tabPanelModifTxtTempMax,
              tabPanelModifTxtTempMin,
              tabPanelModifTxtTiemAbr,
              tabPanelModifTxtTiemNoRefri },
          tabPanelModifRadBtnCadeFrio);
    }
  }// GEN-LAST:event_tabPanelModifBtnModifActionPerformed

  private void tabPanelModifTxtCodPropertyChange() {// GEN-FIRST:event_tabPanelModifTxtCodPropertyChange
    // TODO add your handling code here:

  }// GEN-LAST:event_tabPanelModifTxtCodPropertyChange

  private void tabPanelAgTxtCodKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tabPanelAgTxtCodKeyReleased
    // TODO add your handling code here:
    c.validarCodigoMed(tabPanelAgTxtCod.getText(), warningCod);
  }// GEN-LAST:event_tabPanelAgTxtCodKeyReleased

  private void tabPanelAgTxtNombKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tabPanelAgTxtNombKeyReleased
    // TODO add your handling code here:
    c.validarNombre(tabPanelAgTxtNomb.getText(), warningNom);
  }// GEN-LAST:event_tabPanelAgTxtNombKeyReleased

  private void tabPanelAgTxtFechaVenceKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tabPanelAgTxtFechaVenceKeyReleased
    // TODO add your handling code here:
    c.validarFecha(tabPanelAgTxtFechaVence.getText(), warningFecha);
  }// GEN-LAST:event_tabPanelAgTxtFechaVenceKeyReleased

  private void tabPanelAgTxtUnidDispoKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tabPanelAgTxtUnidDispoKeyReleased
    // TODO add your handling code here:
    c.validarNatural(tabPanelAgTxtUnidDispo.getText(), warningUnidDispo);
  }// GEN-LAST:event_tabPanelAgTxtUnidDispoKeyReleased

  private void tabPanelAgTxtOferKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tabPanelAgTxtOferKeyReleased
    // TODO add your handling code here:
    c.validarOferta(tabPanelAgTxtOfer.getText(), warningOf);
  }// GEN-LAST:event_tabPanelAgTxtOferKeyReleased

  private void tabPanelAgTxtNoAlmaKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tabPanelAgTxtNoAlmaKeyReleased
    // TODO add your handling code here:
    c.validarNoAlma(tabPanelAgTxtNoAlma.getText(), warningNoAlma);// si tiene alma +
  }// GEN-LAST:event_tabPanelAgTxtNoAlmaKeyReleased

  private void tabPanelAgTxtTempMaxKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tabPanelAgTxtTempMaxKeyReleased
    // TODO add your handling code here:
    c.validarTemp(tabPanelAgTxtTempMax.getText(), tabPanelAgTxtTempMin.getText(), warningTempMax);
  }// GEN-LAST:event_tabPanelAgTxtTempMaxKeyReleased

  private void tabPanelAgTxtTempMinKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tabPanelAgTxtTempMinKeyReleased
    // TODO add your handling code here:
    c.validarTemp(tabPanelAgTxtTempMax.getText(), tabPanelAgTxtTempMin.getText(), warningTempMin);
  }// GEN-LAST:event_tabPanelAgTxtTempMinKeyReleased

  private void tabPanelAgTxtTiemNoRefriKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tabPanelAgTxtTiemNoRefriKeyReleased
    // TODO add your handling code here:
    c.validarHoras(tabPanelAgTxtTiemNoRefri.getText(), warningHorRefri);
  }// GEN-LAST:event_tabPanelAgTxtTiemNoRefriKeyReleased

  private void tabPanelAgTxtTiemAbrKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tabPanelAgTxtTiemAbrKeyReleased
    // TODO add your handling code here:
    c.validarHoras(tabPanelAgTxtTiemAbr.getText(), warningTiempAbrir);
  }// GEN-LAST:event_tabPanelAgTxtTiemAbrKeyReleased

  private void tabPanelAgBtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelAgBtnBorrarActionPerformed
    // TODO add your handling code here:
    c.limpiar(new JTextField[] {
        tabPanelAgTxtCod,
        tabPanelAgTxtCostoCompra,
        tabPanelAgTxtFechaVence,
        tabPanelAgTxtNoAlma,
        tabPanelAgTxtNomb,
        tabPanelAgTxtOfer,
        tabPanelAgTxtTempMax,
        tabPanelAgTxtTempMin,
        tabPanelAgTxtTiemAbr,
        tabPanelAgTxtTiemNoRefri,
        tabPanelAgTxtUnidDispo,
        tabPanelAgTxtLote
    }, tabPanelAgCmbVig, tabPanelAgCmbTipMed, tabPanelAgRadBtnCadeFrio);
    c.ocultarIcon(new JLabel[] {
        warningCod, warningNom,
        warningFecha,
        warningUnidDispo,
        warningCosto,
        warningOf,
        warningNoAlma,
        warningTempMax,
        warningTempMin,
        warningHorRefri,
        warningTiempAbrir,
        warningLote
    });
  }// GEN-LAST:event_tabPanelAgBtnBorrarActionPerformed

  private void tabPanelAgTxtOferActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelAgTxtOferActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelAgTxtOferActionPerformed

  private void tabPanelAgTxtTiemAbrActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelAgTxtTiemAbrActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelAgTxtTiemAbrActionPerformed

  private void tabPanelAgTxtTiemNoRefriActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelAgTxtTiemNoRefriActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelAgTxtTiemNoRefriActionPerformed

  private void tabPanelAgTxtTempMinActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelAgTxtTempMinActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelAgTxtTempMinActionPerformed

  private void tabPanelAgTxtUnidDispoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelAgTxtUnidDispoActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelAgTxtUnidDispoActionPerformed

  private void tabPanelAgRadBtnCadeFrioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelAgRadBtnCadeFrioActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelAgRadBtnCadeFrioActionPerformed

  private void tabPanelAgTxtNoAlmaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelAgTxtNoAlmaActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelAgTxtNoAlmaActionPerformed

  private void tabPanelAgTogBtnAggOferActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelAgTogBtnAggOferActionPerformed
    // TODO add your handling code here:
    if (tabPanelAgTogBtnAggOfer.isSelected()) {
      c.mostrarOferta(tabPanelAgTxtOfer, tabPanelAgLblEjOfer);
    } else {
      c.ocultarOferta(tabPanelAgTxtOfer, tabPanelAgLblEjOfer);
    }

  }// GEN-LAST:event_tabPanelAgTogBtnAggOferActionPerformed

  private void tabPanelAgTxtTempMaxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelAgTxtTempMaxActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelAgTxtTempMaxActionPerformed

  private void tabPanelAgTxtFechaVenceActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelAgTxtFechaVenceActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelAgTxtFechaVenceActionPerformed

  private void tabPanelAgCmbTipMedActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelAgCmbTipMedActionPerformed
    // TODO add your handling code here:
    switch (tabPanelAgCmbTipMed.getSelectedIndex()) {
      case 0 -> {
        c.ocultarOpcTipoMed(new JLabel[] { tabPanelAgLblTempMax, tabPanelAgLblTempMin, tabPanelAgLblTiemNoRefri,
            tabPanelAgLblTiemAbr, tabPanelAgLblNoAlma, tabPanelAgLblEjNoAlma, tabPanelAgLblCelsius1,
            tabPanelAgLblCelsius2 },
            new JTextField[] { tabPanelAgTxtTempMin, tabPanelAgTxtNoAlma, tabPanelAgTxtTiemNoRefri,
                tabPanelAgTxtTempMax, tabPanelAgTxtTiemAbr },
            tabPanelAgRadBtnCadeFrio, tabPanelModifTogBtnAggOfer);
        c.ocultarIcon(new JLabel[] {

            warningNoAlma,
            warningTempMax,
            warningTempMin,
            warningHorRefri,
            warningTiempAbrir
        });
      }
      case 1 -> {
        c.ocultarOpcMedNoRefri(tabPanelAgLblNoAlma, tabPanelAgTxtNoAlma, tabPanelAgLblEjNoAlma);
        c.ocultarIcon(new JLabel[] {
            warningNoAlma
        });
        c.mostrarOpcMedRefri(new JLabel[] { tabPanelAgLblTempMax, tabPanelAgLblTempMin,
            tabPanelAgLblTiemNoRefri, tabPanelAgLblTiemAbr, tabPanelAgLblCelsius1, tabPanelAgLblCelsius2 },
            new JTextField[] { tabPanelAgTxtTempMin, tabPanelAgTxtTiemNoRefri, tabPanelAgTxtTempMax,
                tabPanelAgTxtTiemAbr },
            tabPanelAgRadBtnCadeFrio);
      }
      case 2 -> {
        c.ocultarOpcMedRefri(new JLabel[] { tabPanelAgLblTempMax, tabPanelAgLblTempMin,
            tabPanelAgLblTiemNoRefri, tabPanelAgLblTiemAbr, tabPanelAgLblCelsius1, tabPanelAgLblCelsius2 },
            new JTextField[] { tabPanelAgTxtTempMin, tabPanelAgTxtTiemNoRefri, tabPanelAgTxtTempMax,
                tabPanelAgTxtTiemAbr },
            tabPanelAgRadBtnCadeFrio);
        c.ocultarIcon(new JLabel[] {
            warningTempMax,
            warningTempMin,
            warningHorRefri,
            warningTiempAbrir
        });
        c.mostrarOpcMedNoRefri(tabPanelAgLblNoAlma, tabPanelAgTxtNoAlma, tabPanelAgLblEjNoAlma);

      }
    }
  }// GEN-LAST:event_tabPanelAgCmbTipMedActionPerformed

  private void tabPanelAgTxtCodActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelAgTxtCodActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelAgTxtCodActionPerformed

  private void tabPanelAgTxtNombActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelAgTxtNombActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelAgTxtNombActionPerformed

  private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox1ActionPerformed
    // TODO add your handling code here:
    c.ocultarOpcTipoMed(new JLabel[] { tabPanelModifLblCod, tabPanelModifLblFechaVence, tabPanelModifLblUnidDispo,
        tabPanelModifLblUnidVend, tabPanelModifLblCostoCompra, tabPanelModifLblNoAlma, tabPanelModifLblTempMax,
        tabPanelModifLblTempMin, tabPanelModifLblTiemNoRefri, tabPanelModifLblTiemAbr, tabPanelModifLblEjCod,
        tabPanelModifLblNomb, tabPanelModifLblEjFecha, tabPanelModifLblEjOfer, tabPanelModifLblEjNoAlma,
        tabPanelModifLblCelsius1, tabPanelModifLblCelsius2, tabPanelModifLblLote },
        new javax.swing.JTextField[] {
            tabPanelModifTxtCod,
            tabPanelModifTxtCostoCompra,
            tabPanelModifTxtFechaVence,
            tabPanelModifTxtNoAlma,
            tabPanelModifTxtNomb,
            tabPanelModifTxtOfer,
            tabPanelModifTxtTempMax,
            tabPanelModifTxtTempMin,
            tabPanelModifTxtTiemAbr,
            tabPanelModifTxtTiemNoRefri,
            tabPanelModifTxtUnidDispo,
            tabPanelModifTxtUnidVend,
            tabPanelModifTxtLote},
        new JButton[] { tabPanelModifBtnBorrar, tabPanelModifBtnRealizarCambios },
        tabPanelModifCmbVig, tabPanelModifRadBtnCadeFrio, tabPanelModifTogBtnAggOfer);
    
    c.ocultarIcon(new JLabel[] {
        warningCod1,
        warningNom1,
        warningFecha1,
        warningUnidDispo1,
        warningCosto1,
        warningOf1,
        warningNoAlma1,
        warningTempMax1,
        warningTempMin1,
        warningHorRefri1,
        warningTiempAbrir1,
        warningLote1,
        warningUnidVend
    });
    
    c.ocultarIcon(new JLabel[] {
        warningCod,
        warningNom,
        warningFecha,
        warningUnidDispo,
        warningCosto,
        warningOf,
        warningNoAlma,
        warningTempMax,
        warningTempMin,
        warningHorRefri,
        warningTiempAbrir,
        warningLote
    });

    c.limpiar(new JTextField[] {
        tabPanelModifTxtCod,
        tabPanelModifTxtCostoCompra,
        tabPanelModifTxtFechaVence,
        tabPanelModifTxtNoAlma,
        tabPanelModifTxtNomb,
        tabPanelModifTxtOfer,
        tabPanelModifTxtTempMax,
        tabPanelModifTxtTempMin,
        tabPanelModifTxtTiemAbr,
        tabPanelModifTxtTiemNoRefri,
        tabPanelModifTxtUnidDispo,
        tabPanelModifTxtUnidVend,tabPanelModifTxtLote
    }, tabPanelModifCmbVig, tabPanelModifRadBtnCadeFrio);
    

    c.mostrarInfo(jTextArea1, jComboBox1.getSelectedIndex());
    jLayeredPane1.setLayer(jButton1, javax.swing.JLayeredPane.PALETTE_LAYER);
  }// GEN-LAST:event_jComboBox1ActionPerformed

  private void tabPanelModifTxtNombActionPerformed() {// GEN-FIRST:event_tabPanelModifTxtNombActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifTxtNombActionPerformed

  private void tabPanelModifTxtCodActionPerformed() {// GEN-FIRST:event_tabPanelModifTxtCodActionPerformed
    // TODO add your handling code here:
    c.validarCodigoMed(tabPanelModifTxtCod.getText(), warningCod1);
  }// GEN-LAST:event_tabPanelModifTxtCodActionPerformed

  private void tabPanelModifTxtFechaVenceActionPerformed() {// GEN-FIRST:event_tabPanelModifTxtFechaVenceActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifTxtFechaVenceActionPerformed

  private void tabPanelModifTxtTempMaxActionPerformed() {// GEN-FIRST:event_tabPanelModifTxtTempMaxActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifTxtTempMaxActionPerformed

  private void tabPanelModifTogBtnAggOferActionPerformed() {// GEN-FIRST:event_tabPanelModifTogBtnAggOferActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifTogBtnAggOferActionPerformed

  private void tabPanelModifTxtNoAlmaActionPerformed() {// GEN-FIRST:event_tabPanelModifTxtNoAlmaActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifTxtNoAlmaActionPerformed

  private void tabPanelModifRadBtnCadeFrioActionPerformed() {// GEN-FIRST:event_tabPanelModifRadBtnCadeFrioActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifRadBtnCadeFrioActionPerformed

  private void tabPanelModifTxtUnidDispoActionPerformed() {// GEN-FIRST:event_tabPanelModifTxtUnidDispoActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifTxtUnidDispoActionPerformed

  private void tabPanelModifTxtTempMinActionPerformed() {// GEN-FIRST:event_tabPanelModifTxtTempMinActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifTxtTempMinActionPerformed

  private void tabPanelModifTxtTiemNoRefriActionPerformed() {// GEN-FIRST:event_tabPanelModifTxtTiemNoRefriActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifTxtTiemNoRefriActionPerformed

  private void tabPanelModifTxtTiemAbrActionPerformed() {// GEN-FIRST:event_tabPanelModifTxtTiemAbrActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifTxtTiemAbrActionPerformed

  private void tabPanelModifTxtOferActionPerformed() {// GEN-FIRST:event_tabPanelModifTxtOferActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifTxtOferActionPerformed

  private void tabPanelModifBtnBorrarActionPerformed() {// GEN-FIRST:event_tabPanelModifBtnBorrarActionPerformed
    // TODO add your handling code here:

  }// GEN-LAST:event_tabPanelModifBtnBorrarActionPerformed

  private void tabPanelModifCmbVigActionPerformed() {// GEN-FIRST:event_tabPanelModifCmbVigActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifCmbVigActionPerformed

  private void tabPanelModifBtnElimActionPerformed() {// GEN-FIRST:event_tabPanelModifBtnElimActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifBtnElimActionPerformed

  /**
   * @param args the command line arguments
   */
  private javax.swing.JButton jButton1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JPanel tabPanelAg;
    private javax.swing.JButton tabPanelAgBtnAgg;
    private javax.swing.JButton tabPanelAgBtnBorrar;
    private javax.swing.JComboBox<String> tabPanelAgCmbTipMed;
    private javax.swing.JComboBox<String> tabPanelAgCmbVig;
    private javax.swing.JLabel tabPanelAgIconoFondo;
    private javax.swing.JLabel tabPanelAgLblCelsius1;
    private javax.swing.JLabel tabPanelAgLblCelsius2;
    private javax.swing.JLabel tabPanelAgLblCod;
    private javax.swing.JLabel tabPanelAgLblCostoCompra;
    private javax.swing.JLabel tabPanelAgLblEjCod;
    private javax.swing.JLabel tabPanelAgLblEjFecha;
    private javax.swing.JLabel tabPanelAgLblEjNoAlma;
    private javax.swing.JLabel tabPanelAgLblEjOfer;
    private javax.swing.JLabel tabPanelAgLblFechaVence;
    private javax.swing.JLabel tabPanelAgLblNoAlma;
    private javax.swing.JLabel tabPanelAgLblNomb;
    private javax.swing.JLabel tabPanelAgLblTempMax;
    private javax.swing.JLabel tabPanelAgLblTempMin;
    private javax.swing.JLabel tabPanelAgLblTiemAbr;
    private javax.swing.JLabel tabPanelAgLblTiemNoRefri;
    private javax.swing.JLabel tabPanelAgLblUnidDispo;
    private javax.swing.JRadioButton tabPanelAgRadBtnCadeFrio;
    private javax.swing.JToggleButton tabPanelAgTogBtnAggOfer;
    private javax.swing.JTextField tabPanelAgTxtCod;
    private javax.swing.JTextField tabPanelAgTxtCostoCompra;
    private javax.swing.JTextField tabPanelAgTxtFechaVence;
    private javax.swing.JTextField tabPanelAgTxtLote;
    private javax.swing.JTextField tabPanelAgTxtNoAlma;
    private javax.swing.JTextField tabPanelAgTxtNomb;
    private javax.swing.JTextField tabPanelAgTxtOfer;
    private javax.swing.JTextField tabPanelAgTxtTempMax;
    private javax.swing.JTextField tabPanelAgTxtTempMin;
    private javax.swing.JTextField tabPanelAgTxtTiemAbr;
    private javax.swing.JTextField tabPanelAgTxtTiemNoRefri;
    private javax.swing.JTextField tabPanelAgTxtUnidDispo;
    private javax.swing.JLabel tabPanelAglblLote;
    private javax.swing.JPanel tabPanelModif;
    private javax.swing.JButton tabPanelModifBtnBorrar;
    private javax.swing.JButton tabPanelModifBtnElim;
    private javax.swing.JButton tabPanelModifBtnModif;
    private javax.swing.JButton tabPanelModifBtnRealizarCambios;
    private javax.swing.JComboBox<String> tabPanelModifCmbVig;
    private javax.swing.JLabel tabPanelModifLblCelsius1;
    private javax.swing.JLabel tabPanelModifLblCelsius2;
    private javax.swing.JLabel tabPanelModifLblCod;
    private javax.swing.JLabel tabPanelModifLblCostoCompra;
    private javax.swing.JLabel tabPanelModifLblEjCod;
    private javax.swing.JLabel tabPanelModifLblEjFecha;
    private javax.swing.JLabel tabPanelModifLblEjNoAlma;
    private javax.swing.JLabel tabPanelModifLblEjOfer;
    private javax.swing.JLabel tabPanelModifLblFechaVence;
    private javax.swing.JLabel tabPanelModifLblLote;
    private javax.swing.JLabel tabPanelModifLblNoAlma;
    private javax.swing.JLabel tabPanelModifLblNomb;
    private javax.swing.JLabel tabPanelModifLblTempMax;
    private javax.swing.JLabel tabPanelModifLblTempMin;
    private javax.swing.JLabel tabPanelModifLblTiemAbr;
    private javax.swing.JLabel tabPanelModifLblTiemNoRefri;
    private javax.swing.JLabel tabPanelModifLblUnidDispo;
    private javax.swing.JLabel tabPanelModifLblUnidVend;
    private javax.swing.JRadioButton tabPanelModifRadBtnCadeFrio;
    private javax.swing.JToggleButton tabPanelModifTogBtnAggOfer;
    private javax.swing.JTextField tabPanelModifTxtCod;
    private javax.swing.JTextField tabPanelModifTxtCostoCompra;
    private javax.swing.JTextField tabPanelModifTxtFechaVence;
    private javax.swing.JTextField tabPanelModifTxtLote;
    private javax.swing.JTextField tabPanelModifTxtNoAlma;
    private javax.swing.JTextField tabPanelModifTxtNomb;
    private javax.swing.JTextField tabPanelModifTxtOfer;
    private javax.swing.JTextField tabPanelModifTxtTempMax;
    private javax.swing.JTextField tabPanelModifTxtTempMin;
    private javax.swing.JTextField tabPanelModifTxtTiemAbr;
    private javax.swing.JTextField tabPanelModifTxtTiemNoRefri;
    private javax.swing.JTextField tabPanelModifTxtUnidDispo;
    private javax.swing.JTextField tabPanelModifTxtUnidVend;
    private javax.swing.JLabel warningCod;
    private javax.swing.JLabel warningCod1;
    private javax.swing.JLabel warningCosto;
    private javax.swing.JLabel warningCosto1;
    private javax.swing.JLabel warningFecha;
    private javax.swing.JLabel warningFecha1;
    private javax.swing.JLabel warningHorRefri;
    private javax.swing.JLabel warningHorRefri1;
    private javax.swing.JLabel warningLote;
    private javax.swing.JLabel warningLote1;
    private javax.swing.JLabel warningNoAlma;
    private javax.swing.JLabel warningNoAlma1;
    private javax.swing.JLabel warningNom;
    private javax.swing.JLabel warningNom1;
    private javax.swing.JLabel warningOf;
    private javax.swing.JLabel warningOf1;
    private javax.swing.JLabel warningTempMax;
    private javax.swing.JLabel warningTempMax1;
    private javax.swing.JLabel warningTempMin;
    private javax.swing.JLabel warningTempMin1;
    private javax.swing.JLabel warningTiempAbrir;
    private javax.swing.JLabel warningTiempAbrir1;
    private javax.swing.JLabel warningUnidDispo;
    private javax.swing.JLabel warningUnidDispo1;
    private javax.swing.JLabel warningUnidVend;
    // End of variables declaration//GEN-END:variables
}
