/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventariox.genia.vista;

import inventariox.genia.ListaMedicamentos;
import inventariox.genia.controladora.Controladora;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author honey
 */
public class PantallaEmpleado extends javax.swing.JFrame {
  Controladora c;

  /**
   * Creates new form PantallaEmpleado
   */
  public PantallaEmpleado(ListaMedicamentos lista) {
    c = new Controladora(lista);
    initComponents();
    c.ocultarOpcTipoMed(new JLabel[] { tabPanelModifLblCod, tabPanelModifLblFechaVence, tabPanelModifLblUnidDispo,
        tabPanelModifLblUnidVend, tabPanelModifLblCostoCompra, tabPanelModifLblNoAlma, tabPanelModifLblTempMax,
        tabPanelModifLblTempMin, tabPanelModifLblTiemNoRefri, tabPanelModifLblTiemAbr, tabPanelModifLblEjCod,
        tabPanelModifLblNomb, tabPanelModifLblEjFecha, tabPanelModifLblEjOfer, tabPanelModifLblEjNoAlma,
        tabPanelModifLblCelsius1, tabPanelModifLblCelsius2} , new javax.swing.JTextField[] {
        tabPanelModifTxtCod,
        tabPanelModifTxtCostoCompra,
        tabPanelModifTxtFechaVence,
        tabPanelModifTxtNoAlma,
        tabPanelModifTxtNomb,
        tabPanelModifTxtOfer,
        tabPanelModifTxtTempMax,
        tabPanelModifTxtTempMin,
        tabPanelModifTxtTiemAbr,
        tabPanelModifTxtTiemNoRefri,
        tabPanelModifTxtUnidDispo,
        tabPanelModifTxtUnidVend}, new JButton[]{tabPanelModifBtnBorrar,tabPanelModifBtnRealizarCambios},
        tabPanelModifCmbVig,tabPanelModifRadBtnCadeFrio, tabPanelModifTogBtnAggOfer);
    // de Med Refrigerado
  }

  public JComboBox<String> getjComboBox1() {
    return jComboBox1;
  }

  public void setjComboBox1(JComboBox<String> jComboBox1) {
    this.jComboBox1 = jComboBox1;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabPanelAg = new javax.swing.JPanel();
        tabPanelAgCmbVig = new javax.swing.JComboBox<>();
        tabPanelAgTxtNomb = new javax.swing.JTextField();
        tabPanelAgLblCod = new javax.swing.JLabel();
        tabPanelAgTxtCod = new javax.swing.JTextField();
        tabPanelAgCmbTipMed = new javax.swing.JComboBox<>();
        tabPanelAgLblFechaVence = new javax.swing.JLabel();
        tabPanelAgTxtFechaVence = new javax.swing.JTextField();
        tabPanelAgLblUnidDispo = new javax.swing.JLabel();
        tabPanelAgTxtTempMax = new javax.swing.JTextField();
        tabPanelAgTxtUnidVend = new javax.swing.JTextField();
        tabPanelAgLblUnidVend = new javax.swing.JLabel();
        tabPanelAgLblCostoCompra = new javax.swing.JLabel();
        tabPanelAgTxtCostoCompra = new javax.swing.JTextField();
        tabPanelAgTogBtnAggOfer = new javax.swing.JToggleButton();
        tabPanelAgLblNoAlma = new javax.swing.JLabel();
        tabPanelAgTxtNoAlma = new javax.swing.JTextField();
        tabPanelAgRadBtnCadeFrio = new javax.swing.JRadioButton();
        tabPanelAgLblTempMax = new javax.swing.JLabel();
        tabPanelAgTxtUnidDispo = new javax.swing.JTextField();
        tabPanelAgTxtTempMin = new javax.swing.JTextField();
        tabPanelAgLblTempMin = new javax.swing.JLabel();
        tabPanelAgLblTiemNoRefri = new javax.swing.JLabel();
        tabPanelAgTxtTiemNoRefri = new javax.swing.JTextField();
        tabPanelAgLblTiemAbr = new javax.swing.JLabel();
        tabPanelAgTxtTiemAbr = new javax.swing.JTextField();
        tabPanelAgTxtOfer = new javax.swing.JTextField();
        tabPanelAgLblEjCod = new javax.swing.JLabel();
        tabPanelAgLblNomb = new javax.swing.JLabel();
        tabPanelAgLblEjFecha = new javax.swing.JLabel();
        tabPanelAgLblEjOfer = new javax.swing.JLabel();
        tabPanelAgLblEjNoAlma = new javax.swing.JLabel();
        tabPanelAgLblCelsius1 = new javax.swing.JLabel();
        tabPanelAgLblCelsius2 = new javax.swing.JLabel();
        tabPanelAgBtnAgg = new javax.swing.JButton();
        tabPanelAgBtnBorrar = new javax.swing.JButton();
        tabPanelAgIconoFondo = new javax.swing.JLabel();
        tabPanelModif = new javax.swing.JPanel();
        tabPanelModifBtnElim = new javax.swing.JButton();
        tabPanelModifBtnModif = new javax.swing.JButton();
        tabPanelModifCmbVig = new javax.swing.JComboBox<>();
        tabPanelModifTxtNomb = new javax.swing.JTextField();
        tabPanelModifLblCod = new javax.swing.JLabel();
        tabPanelModifTxtCod = new javax.swing.JTextField();
        tabPanelModifLblFechaVence = new javax.swing.JLabel();
        tabPanelModifTxtFechaVence = new javax.swing.JTextField();
        tabPanelModifLblUnidDispo = new javax.swing.JLabel();
        tabPanelModifTxtTempMax = new javax.swing.JTextField();
        tabPanelModifTxtUnidVend = new javax.swing.JTextField();
        tabPanelModifLblUnidVend = new javax.swing.JLabel();
        tabPanelModifLblCostoCompra = new javax.swing.JLabel();
        tabPanelModifTxtCostoCompra = new javax.swing.JTextField();
        tabPanelModifTogBtnAggOfer = new javax.swing.JToggleButton();
        tabPanelModifLblNoAlma = new javax.swing.JLabel();
        tabPanelModifTxtNoAlma = new javax.swing.JTextField();
        tabPanelModifRadBtnCadeFrio = new javax.swing.JRadioButton();
        tabPanelModifLblTempMax = new javax.swing.JLabel();
        tabPanelModifTxtUnidDispo = new javax.swing.JTextField();
        tabPanelModifTxtTempMin = new javax.swing.JTextField();
        tabPanelModifLblTempMin = new javax.swing.JLabel();
        tabPanelModifLblTiemNoRefri = new javax.swing.JLabel();
        tabPanelModifTxtTiemNoRefri = new javax.swing.JTextField();
        tabPanelModifLblTiemAbr = new javax.swing.JLabel();
        tabPanelModifTxtTiemAbr = new javax.swing.JTextField();
        tabPanelModifTxtOfer = new javax.swing.JTextField();
        tabPanelModifLblEjCod = new javax.swing.JLabel();
        tabPanelModifLblNomb = new javax.swing.JLabel();
        tabPanelModifLblEjFecha = new javax.swing.JLabel();
        tabPanelModifLblEjOfer = new javax.swing.JLabel();
        tabPanelModifLblEjNoAlma = new javax.swing.JLabel();
        tabPanelModifLblCelsius1 = new javax.swing.JLabel();
        tabPanelModifLblCelsius2 = new javax.swing.JLabel();
        tabPanelModifBtnRealizarCambios = new javax.swing.JButton();
        tabPanelModifBtnBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/inventariox/genia/vista/pill.png")).getImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1 = new javax.swing.JButton();
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLayeredPane2.setLayer(jButton1, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventariox/genia/vista/antecedentes-medicos-limpios_53876-116873.png"))); // NOI18N
        jLayeredPane2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 600));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Source Code Pro", 0, 14)); // NOI18N
        jLabel2.setText("Seleccione un medicamento:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.setToolTipText("Selecciona el medicamento a modificar");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);
        c.mostrarInfo(jTextArea1, jComboBox1.getSelectedIndex());

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Source Code Pro", 0, 14)); // NOI18N
        jLabel4.setText("Cambios Realizados:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Agregar", tabPanelAg);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tabPanelAg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabPanelAg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabPanelAgCmbVig.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vigencia", "Disponible", "No disponible", "Retirado" }));
        tabPanelAg.add(tabPanelAgCmbVig, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 19, -1, -1));

        tabPanelAgTxtNomb.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelAgTxtNomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelAgTxtNombActionPerformed(evt);
            }
        });
        tabPanelAg.add(tabPanelAgTxtNomb, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 97, 158, -1));

        tabPanelAgLblCod.setText("Ingrese el codigo del producto");
        tabPanelAg.add(tabPanelAgLblCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 22, -1, -1));

        tabPanelAgTxtCod.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelAgTxtCod.setName("Hola"); // NOI18N
        tabPanelAgTxtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelAgTxtCodActionPerformed(evt);
            }
        });
        tabPanelAg.add(tabPanelAgTxtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 55, 158, -1));

        tabPanelAgCmbTipMed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de medicamento", "Refrigerado", "No Refrigerado" }));
        tabPanelAgCmbTipMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelAgCmbTipMedActionPerformed(evt);
            }
        });
        tabPanelAg.add(tabPanelAgCmbTipMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 55, -1, -1));

        tabPanelAgLblFechaVence.setText("Fecha Vencimiento");
        tabPanelAg.add(tabPanelAgLblFechaVence, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 139, -1, -1));

        tabPanelAgTxtFechaVence.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelAgTxtFechaVence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelAgTxtFechaVenceActionPerformed(evt);
            }
        });
        tabPanelAg.add(tabPanelAgTxtFechaVence, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 169, 100, -1));

        tabPanelAgLblUnidDispo.setText("Unidades Disponibles");
        tabPanelAg.add(tabPanelAgLblUnidDispo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 205, -1, -1));

        tabPanelAgTxtTempMax.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelAgTxtTempMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelAgTxtTempMaxActionPerformed(evt);
            }
        });
        tabPanelAg.add(tabPanelAgTxtTempMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 169, 120, -1));

        tabPanelAgTxtUnidVend.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelAg.add(tabPanelAgTxtUnidVend, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 295, 136, -1));

        tabPanelAgLblUnidVend.setText("Unidades Vendidas");
        tabPanelAg.add(tabPanelAgLblUnidVend, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 265, -1, -1));

        tabPanelAgLblCostoCompra.setText("Costo de Compra");
        tabPanelAg.add(tabPanelAgLblCostoCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 325, -1, -1));

        tabPanelAgTxtCostoCompra.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelAg.add(tabPanelAgTxtCostoCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 355, 136, -1));

        tabPanelAgTogBtnAggOfer.setText("Agregar Oferta");
        tabPanelAgTogBtnAggOfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelAgTogBtnAggOferActionPerformed(evt);
            }
        });
        tabPanelAg.add(tabPanelAgTogBtnAggOfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 391, -1, -1));

        tabPanelAgLblNoAlma.setText("No almacenar en");
        tabPanelAg.add(tabPanelAgLblNoAlma, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 475, -1, -1));

        tabPanelAgTxtNoAlma.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelAgTxtNoAlma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelAgTxtNoAlmaActionPerformed(evt);
            }
        });
        tabPanelAg.add(tabPanelAgTxtNoAlma, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 505, 142, -1));

        tabPanelAgRadBtnCadeFrio.setText("Certificado de Cadena de Frio");
        tabPanelAgRadBtnCadeFrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelAgRadBtnCadeFrioActionPerformed(evt);
            }
        });
        tabPanelAg.add(tabPanelAgRadBtnCadeFrio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 98, -1, -1));

        tabPanelAgLblTempMax.setText("Temperatura MAX");
        tabPanelAg.add(tabPanelAgLblTempMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 139, -1, -1));

        tabPanelAgTxtUnidDispo.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelAgTxtUnidDispo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelAgTxtUnidDispoActionPerformed(evt);
            }
        });
        tabPanelAg.add(tabPanelAgTxtUnidDispo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 235, 136, -1));

        tabPanelAgTxtTempMin.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelAgTxtTempMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelAgTxtTempMinActionPerformed(evt);
            }
        });
        tabPanelAg.add(tabPanelAgTxtTempMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 235, 120, -1));

        tabPanelAgLblTempMin.setText("Temperatura MIN");
        tabPanelAg.add(tabPanelAgLblTempMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 205, -1, -1));

        tabPanelAgLblTiemNoRefri.setText("Horas sin refrigeracion");
        tabPanelAg.add(tabPanelAgLblTiemNoRefri, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 271, -1, -1));

        tabPanelAgTxtTiemNoRefri.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelAgTxtTiemNoRefri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelAgTxtTiemNoRefriActionPerformed(evt);
            }
        });
        tabPanelAg.add(tabPanelAgTxtTiemNoRefri, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 295, 165, -1));

        tabPanelAgLblTiemAbr.setText("Duracion despues de abrirlo");
        tabPanelAg.add(tabPanelAgLblTiemAbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 325, -1, -1));

        tabPanelAgTxtTiemAbr.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelAgTxtTiemAbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelAgTxtTiemAbrActionPerformed(evt);
            }
        });
        tabPanelAg.add(tabPanelAgTxtTiemAbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 355, 171, -1));

        tabPanelAgTxtOfer.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelAgTxtOfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelAgTxtOferActionPerformed(evt);
            }
        });
        tabPanelAg.add(tabPanelAgTxtOfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 433, 142, -1));

        tabPanelAgLblEjCod.setText("Ej: AA12345678");
        tabPanelAg.add(tabPanelAgLblEjCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 58, -1, -1));

        tabPanelAgLblNomb.setText("Nombre");
        tabPanelAg.add(tabPanelAgLblNomb, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        tabPanelAgLblEjFecha.setText("MM/AAAA");
        tabPanelAg.add(tabPanelAgLblEjFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 172, -1, -1));

        tabPanelAgLblEjOfer.setText("Escriba el porcentaje (sin %)");
        tabPanelAg.add(tabPanelAgLblEjOfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 436, -1, -1));

        tabPanelAgLblEjNoAlma.setText("Separar con comas");
        tabPanelAg.add(tabPanelAgLblEjNoAlma, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 508, -1, -1));

        tabPanelAgLblCelsius1.setText("Celsius");
        tabPanelAg.add(tabPanelAgLblCelsius1, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 172, -1, -1));

        tabPanelAgLblCelsius2.setText("Celsius");
        tabPanelAg.add(tabPanelAgLblCelsius2, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 238, -1, -1));

        tabPanelAgBtnAgg.setForeground(new java.awt.Color(0, 153, 51));
        tabPanelAgBtnAgg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventariox/genia/vista/anadir.png"))); // NOI18N
        tabPanelAgBtnAgg.setText("AGREGAR");
        tabPanelAgBtnAgg.setToolTipText("Lo agrega al inventario");
        tabPanelAg.add(tabPanelAgBtnAgg, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 397, -1, -1));

        tabPanelAgBtnBorrar.setForeground(new java.awt.Color(255, 0, 51));
        tabPanelAgBtnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventariox/genia/vista/escoba.png"))); // NOI18N
        tabPanelAgBtnBorrar.setText("BORRAR");
        tabPanelAgBtnBorrar.setToolTipText("Borra los datos ingresados (no el producto)");
        tabPanelAgBtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelAgBtnBorrarActionPerformed(evt);
            }
        });
        tabPanelAg.add(tabPanelAgBtnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 397, -1, -1));

        tabPanelAgIconoFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventariox/genia/vista/simbolo-de-la-medicina (1).png"))); // NOI18N
        tabPanelAg.add(tabPanelAgIconoFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jTabbedPane1.addTab("Agregar", new javax.swing.ImageIcon(getClass().getResource("/inventariox/genia/vista/agregar.png")), tabPanelAg, "Agrega un medicamento al inventario"); // NOI18N

        tabPanelModif.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabPanelModif.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabPanelModifBtnElim.setForeground(new java.awt.Color(255, 0, 51));
        tabPanelModifBtnElim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventariox/genia/vista/cancelar.png"))); // NOI18N
        tabPanelModifBtnElim.setText("ELMINAR PRODUCTO");
        tabPanelModifBtnElim.setToolTipText("Elimina el medicamento seleccionado");
        tabPanelModifBtnElim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabPanelModifBtnElim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelModifBtnElimActionPerformed(evt);
            }
        });
        tabPanelModif.add(tabPanelModifBtnElim, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        tabPanelModifBtnModif.setForeground(new java.awt.Color(102, 204, 0));
        tabPanelModifBtnModif.setText("MODIFICAR PRODUCTO");
        tabPanelModifBtnModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelModifBtnModifActionPerformed(evt);
            }
        });
        tabPanelModif.add(tabPanelModifBtnModif, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));

        tabPanelModifCmbVig.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vigencia", "Disponible", "No disponible", "Retirado" }));
        tabPanelModifCmbVig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelModifCmbVigActionPerformed(evt);
            }
        });
        tabPanelModif.add(tabPanelModifCmbVig, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        tabPanelModifTxtNomb.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelModifTxtNomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelModifTxtNombActionPerformed(evt);
            }
        });
        tabPanelModif.add(tabPanelModifTxtNomb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 158, -1));

        tabPanelModifLblCod.setText("Ingrese el codigo del producto");
        tabPanelModif.add(tabPanelModifLblCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        tabPanelModifTxtCod.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelModifTxtCod.setName("Hola"); // NOI18N
        tabPanelModifTxtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelModifTxtCodActionPerformed(evt);
            }
        });
        tabPanelModifTxtCod.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tabPanelModifTxtCodPropertyChange(evt);
            }
        });
        tabPanelModif.add(tabPanelModifTxtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 158, -1));

        tabPanelModifLblFechaVence.setText("Fecha Vencimiento");
        tabPanelModif.add(tabPanelModifLblFechaVence, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        tabPanelModifTxtFechaVence.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelModifTxtFechaVence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelModifTxtFechaVenceActionPerformed(evt);
            }
        });
        tabPanelModif.add(tabPanelModifTxtFechaVence, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 100, -1));

        tabPanelModifLblUnidDispo.setText("Unidades Disponibles");
        tabPanelModif.add(tabPanelModifLblUnidDispo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        tabPanelModifTxtTempMax.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelModifTxtTempMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelModifTxtTempMaxActionPerformed(evt);
            }
        });
        tabPanelModif.add(tabPanelModifTxtTempMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 120, -1));

        tabPanelModifTxtUnidVend.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelModif.add(tabPanelModifTxtUnidVend, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 136, -1));

        tabPanelModifLblUnidVend.setText("Unidades Vendidas");
        tabPanelModif.add(tabPanelModifLblUnidVend, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        tabPanelModifLblCostoCompra.setText("Costo de Compra");
        tabPanelModif.add(tabPanelModifLblCostoCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        tabPanelModifTxtCostoCompra.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelModif.add(tabPanelModifTxtCostoCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 136, -1));

        tabPanelModifTogBtnAggOfer.setText("Agregar Oferta");
        tabPanelModifTogBtnAggOfer.setVisible(false);
        tabPanelModifTogBtnAggOfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelModifTogBtnAggOferActionPerformed(evt);
            }
        });
        tabPanelModif.add(tabPanelModifTogBtnAggOfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        tabPanelModifLblNoAlma.setText("No almacenar en");
        tabPanelModif.add(tabPanelModifLblNoAlma, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, -1));

        tabPanelModifTxtNoAlma.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelModifTxtNoAlma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelModifTxtNoAlmaActionPerformed(evt);
            }
        });
        tabPanelModif.add(tabPanelModifTxtNoAlma, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 142, -1));

        tabPanelModifRadBtnCadeFrio.setVisible(false);
        tabPanelModifRadBtnCadeFrio.setText("Certificado de Cadena de Frio");
        tabPanelModifRadBtnCadeFrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelModifRadBtnCadeFrioActionPerformed(evt);
            }
        });
        tabPanelModif.add(tabPanelModifRadBtnCadeFrio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));

        tabPanelModifLblTempMax.setText("Temperatura MAX");
        tabPanelModif.add(tabPanelModifLblTempMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        tabPanelModifTxtUnidDispo.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelModifTxtUnidDispo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelModifTxtUnidDispoActionPerformed(evt);
            }
        });
        tabPanelModif.add(tabPanelModifTxtUnidDispo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 136, -1));

        tabPanelModifTxtTempMin.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelModifTxtTempMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelModifTxtTempMinActionPerformed(evt);
            }
        });
        tabPanelModif.add(tabPanelModifTxtTempMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 120, -1));

        tabPanelModifLblTempMin.setText("Temperatura MIN");
        tabPanelModif.add(tabPanelModifLblTempMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        tabPanelModifLblTiemNoRefri.setText("Horas sin refrigeracion");
        tabPanelModif.add(tabPanelModifLblTiemNoRefri, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        tabPanelModifTxtTiemNoRefri.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelModifTxtTiemNoRefri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelModifTxtTiemNoRefriActionPerformed(evt);
            }
        });
        tabPanelModif.add(tabPanelModifTxtTiemNoRefri, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 165, -1));

        tabPanelModifLblTiemAbr.setText("Duracion despues de abrirlo");
        tabPanelModif.add(tabPanelModifLblTiemAbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, -1));

        tabPanelModifTxtTiemAbr.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelModifTxtTiemAbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelModifTxtTiemAbrActionPerformed(evt);
            }
        });
        tabPanelModif.add(tabPanelModifTxtTiemAbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 171, -1));

        tabPanelModifTxtOfer.setForeground(new java.awt.Color(126, 126, 126));
        tabPanelModifTxtOfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelModifTxtOferActionPerformed(evt);
            }
        });
        tabPanelModif.add(tabPanelModifTxtOfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 142, -1));

        tabPanelModifLblEjCod.setText("Ej: AA12345678");
        tabPanelModif.add(tabPanelModifLblEjCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        tabPanelModifLblNomb.setText("Nombre");
        tabPanelModif.add(tabPanelModifLblNomb, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        tabPanelModifLblEjFecha.setText("MM/AAAA");
        tabPanelModif.add(tabPanelModifLblEjFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        tabPanelModifLblEjOfer.setText("Escriba el porcentaje (sin %)");
        tabPanelModif.add(tabPanelModifLblEjOfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, -1, -1));

        tabPanelModifLblEjNoAlma.setText("Separar con comas");
        tabPanelModif.add(tabPanelModifLblEjNoAlma, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, -1, -1));

        tabPanelModifLblCelsius1.setText("Celsius");
        tabPanelModif.add(tabPanelModifLblCelsius1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        tabPanelModifLblCelsius2.setText("Celsius");
        tabPanelModif.add(tabPanelModifLblCelsius2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, -1));

        tabPanelModifBtnRealizarCambios.setForeground(new java.awt.Color(0, 153, 51));
        tabPanelModifBtnRealizarCambios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventariox/genia/vista/anadir.png"))); // NOI18N
        tabPanelModifBtnRealizarCambios.setText("Relizar Cambios");
        tabPanelModifBtnRealizarCambios.setToolTipText("Agregar Cambios");
        tabPanelModif.add(tabPanelModifBtnRealizarCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, -1, -1));

        tabPanelModifBtnBorrar.setForeground(new java.awt.Color(255, 0, 51));
        tabPanelModifBtnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventariox/genia/vista/escoba.png"))); // NOI18N
        tabPanelModifBtnBorrar.setText("BORRAR");
        tabPanelModifBtnBorrar.setToolTipText("Borra los datos ingresados (no el producto)");
        tabPanelModifBtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabPanelModifBtnBorrarActionPerformed(evt);
            }
        });
        tabPanelModif.add(tabPanelModifBtnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, -1, -1));

        jTabbedPane1.addTab("Modificar", new javax.swing.ImageIcon(getClass().getResource("/inventariox/genia/vista/lista.png")), tabPanelModif, "Modificar el medicamento seleccionado"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        jLayeredPane1.setLayer(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabPanelModifBtnModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabPanelModifBtnModifActionPerformed
        // TODO add your handling code here:
        c.mostrarOpcModif(new JButton[]{tabPanelModifBtnRealizarCambios,tabPanelModifBtnBorrar},new JLabel[]{tabPanelModifLblCod, tabPanelModifLblFechaVence, tabPanelModifLblUnidDispo,
        tabPanelModifLblUnidVend, tabPanelModifLblCostoCompra,tabPanelModifLblEjCod,
        tabPanelModifLblNomb, tabPanelModifLblEjFecha}, 
        new JTextField[] {tabPanelModifTxtCod,
        tabPanelModifTxtCostoCompra,
        tabPanelModifTxtFechaVence,
        tabPanelModifTxtNomb,tabPanelModifTxtUnidDispo,
        tabPanelModifTxtUnidVend}, tabPanelModifTogBtnAggOfer, tabPanelModifCmbVig);
        
        
        if(c.medNecesitaRefrigeracion(jComboBox1.getSelectedIndex())){
            c.mostrarOpcMedRefri(new JLabel[] {  tabPanelModifLblTempMax,
        tabPanelModifLblTempMin, tabPanelModifLblTiemNoRefri, tabPanelModifLblTiemAbr, //tabPanelModifLblEjOfer,
        tabPanelModifLblCelsius1, tabPanelModifLblCelsius2 }, new javax.swing.JTextField[] {
        tabPanelModifTxtTempMax,
        tabPanelModifTxtTempMin,
        tabPanelModifTxtTiemAbr,
        tabPanelModifTxtTiemNoRefri}, tabPanelModifRadBtnCadeFrio);
        }
    }//GEN-LAST:event_tabPanelModifBtnModifActionPerformed

    private void tabPanelModifTxtCodPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tabPanelModifTxtCodPropertyChange
        // TODO add your handling code here:
        System.out.println(evt);
        System.out.println("HOLA");
    }//GEN-LAST:event_tabPanelModifTxtCodPropertyChange

  private void tabPanelAgBtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelAgBtnBorrarActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelAgBtnBorrarActionPerformed

  private void tabPanelAgTxtOferActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelAgTxtOferActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelAgTxtOferActionPerformed

  private void tabPanelAgTxtTiemAbrActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelAgTxtTiemAbrActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelAgTxtTiemAbrActionPerformed

  private void tabPanelAgTxtTiemNoRefriActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelAgTxtTiemNoRefriActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelAgTxtTiemNoRefriActionPerformed

  private void tabPanelAgTxtTempMinActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelAgTxtTempMinActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelAgTxtTempMinActionPerformed

  private void tabPanelAgTxtUnidDispoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelAgTxtUnidDispoActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelAgTxtUnidDispoActionPerformed

  private void tabPanelAgRadBtnCadeFrioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelAgRadBtnCadeFrioActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelAgRadBtnCadeFrioActionPerformed

  private void tabPanelAgTxtNoAlmaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelAgTxtNoAlmaActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelAgTxtNoAlmaActionPerformed

  private void tabPanelAgTogBtnAggOferActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelAgTogBtnAggOferActionPerformed
    // TODO add your handling code here:
    if (tabPanelAgTogBtnAggOfer.isSelected()) {
      c.mostrarOferta(tabPanelAgTxtOfer, tabPanelAgLblEjOfer);
    } else {
      c.ocultarOferta(tabPanelAgTxtOfer, tabPanelAgLblEjOfer);
    }

  }// GEN-LAST:event_tabPanelAgTogBtnAggOferActionPerformed

  private void tabPanelAgTxtTempMaxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelAgTxtTempMaxActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelAgTxtTempMaxActionPerformed

  private void tabPanelAgTxtFechaVenceActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelAgTxtFechaVenceActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelAgTxtFechaVenceActionPerformed

  private void tabPanelAgCmbTipMedActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelAgCmbTipMedActionPerformed
    // TODO add your handling code here:
    switch (tabPanelAgCmbTipMed.getSelectedIndex()) {
      case 0 -> {
        c.ocultarOpcTipoMed(new JLabel []{tabPanelAgLblTempMax, tabPanelAgLblTempMin,tabPanelAgLblTiemNoRefri,
            tabPanelAgLblTiemAbr, tabPanelAgLblNoAlma, tabPanelAgLblEjNoAlma,tabPanelAgLblCelsius1, tabPanelAgLblCelsius2}, 
            new JTextField []{tabPanelAgTxtTempMin, tabPanelAgTxtNoAlma, tabPanelAgTxtTiemNoRefri, tabPanelAgTxtTempMax, tabPanelAgTxtTiemAbr},
            tabPanelModifRadBtnCadeFrio,tabPanelModifTogBtnAggOfer);
      }
      case 1 -> {
        c.ocultarOpcMedNoRefri(tabPanelAgLblNoAlma, tabPanelAgTxtNoAlma, tabPanelAgLblEjNoAlma);
        c.mostrarOpcMedRefri( new JLabel[]{tabPanelAgLblTempMax, tabPanelAgLblTempMin, 
            tabPanelAgLblTiemNoRefri,tabPanelAgLblTiemAbr, tabPanelAgLblCelsius1,tabPanelAgLblCelsius2},
                new JTextField []{tabPanelAgTxtTempMin,tabPanelAgTxtTiemNoRefri, tabPanelAgTxtTempMax, tabPanelAgTxtTiemAbr},tabPanelModifRadBtnCadeFrio);
      }
      case 2 -> {
        c.ocultarOpcMedRefri(new JLabel[]{tabPanelAgLblTempMax, tabPanelAgLblTempMin, 
            tabPanelAgLblTiemNoRefri,tabPanelAgLblTiemAbr, tabPanelAgLblCelsius1,tabPanelAgLblCelsius2},
                new JTextField []{tabPanelAgTxtTempMin,tabPanelAgTxtTiemNoRefri, tabPanelAgTxtTempMax, tabPanelAgTxtTiemAbr},tabPanelModifRadBtnCadeFrio);
        c.mostrarOpcMedNoRefri(tabPanelAgLblNoAlma, tabPanelAgTxtNoAlma, tabPanelAgLblEjNoAlma);

      }
    }
  }// GEN-LAST:event_tabPanelAgCmbTipMedActionPerformed

  private void tabPanelAgTxtCodActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelAgTxtCodActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelAgTxtCodActionPerformed

  private void tabPanelAgTxtNombActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelAgTxtNombActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelAgTxtNombActionPerformed

  private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox1ActionPerformed
    // TODO add your handling code here:
    c.ocultarOpcTipoMed(new JLabel[] { tabPanelModifLblCod, tabPanelModifLblFechaVence, tabPanelModifLblUnidDispo,
        tabPanelModifLblUnidVend, tabPanelModifLblCostoCompra, tabPanelModifLblNoAlma, tabPanelModifLblTempMax,
        tabPanelModifLblTempMin, tabPanelModifLblTiemNoRefri, tabPanelModifLblTiemAbr, tabPanelModifLblEjCod,
        tabPanelModifLblNomb, tabPanelModifLblEjFecha, tabPanelModifLblEjOfer, tabPanelModifLblEjNoAlma,
        tabPanelModifLblCelsius1, tabPanelModifLblCelsius2} , new javax.swing.JTextField[] {
        tabPanelModifTxtCod,
        tabPanelModifTxtCostoCompra,
        tabPanelModifTxtFechaVence,
        tabPanelModifTxtNoAlma,
        tabPanelModifTxtNomb,
        tabPanelModifTxtOfer,
        tabPanelModifTxtTempMax,
        tabPanelModifTxtTempMin,
        tabPanelModifTxtTiemAbr,
        tabPanelModifTxtTiemNoRefri,
        tabPanelModifTxtUnidDispo,
        tabPanelModifTxtUnidVend}, new JButton[]{tabPanelModifBtnBorrar,tabPanelModifBtnRealizarCambios},
        tabPanelModifCmbVig,tabPanelModifRadBtnCadeFrio, tabPanelModifTogBtnAggOfer);
    tabPanelAgRadBtnCadeFrio.setVisible(false); tabPanelAgTogBtnAggOfer.setVisible(false);
    c.mostrarInfo(jTextArea1, jComboBox1.getSelectedIndex());
    jLayeredPane1.setLayer(jButton1, javax.swing.JLayeredPane.PALETTE_LAYER);
  }// GEN-LAST:event_jComboBox1ActionPerformed

  private void tabPanelModifTxtNombActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelModifTxtNombActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifTxtNombActionPerformed

  private void tabPanelModifTxtCodActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelModifTxtCodActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifTxtCodActionPerformed

  private void tabPanelModifTxtFechaVenceActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelModifTxtFechaVenceActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifTxtFechaVenceActionPerformed

  private void tabPanelModifTxtTempMaxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelModifTxtTempMaxActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifTxtTempMaxActionPerformed

  private void tabPanelModifTogBtnAggOferActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelModifTogBtnAggOferActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifTogBtnAggOferActionPerformed

  private void tabPanelModifTxtNoAlmaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelModifTxtNoAlmaActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifTxtNoAlmaActionPerformed

  private void tabPanelModifRadBtnCadeFrioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelModifRadBtnCadeFrioActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifRadBtnCadeFrioActionPerformed

  private void tabPanelModifTxtUnidDispoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelModifTxtUnidDispoActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifTxtUnidDispoActionPerformed

  private void tabPanelModifTxtTempMinActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelModifTxtTempMinActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifTxtTempMinActionPerformed

  private void tabPanelModifTxtTiemNoRefriActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelModifTxtTiemNoRefriActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifTxtTiemNoRefriActionPerformed

  private void tabPanelModifTxtTiemAbrActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelModifTxtTiemAbrActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifTxtTiemAbrActionPerformed

  private void tabPanelModifTxtOferActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelModifTxtOferActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifTxtOferActionPerformed

  private void tabPanelModifBtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelModifBtnBorrarActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifBtnBorrarActionPerformed

  private void tabPanelModifCmbVigActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelModifCmbVigActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifCmbVigActionPerformed

  private void tabPanelModifBtnElimActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tabPanelModifBtnElimActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_tabPanelModifBtnElimActionPerformed

  /**
   * @param args the command line arguments
   */
  private javax.swing.JButton jButton1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JPanel tabPanelAg;
    private javax.swing.JButton tabPanelAgBtnAgg;
    private javax.swing.JButton tabPanelAgBtnBorrar;
    private javax.swing.JComboBox<String> tabPanelAgCmbTipMed;
    private javax.swing.JComboBox<String> tabPanelAgCmbVig;
    private javax.swing.JLabel tabPanelAgIconoFondo;
    private javax.swing.JLabel tabPanelAgLblCelsius1;
    private javax.swing.JLabel tabPanelAgLblCelsius2;
    private javax.swing.JLabel tabPanelAgLblCod;
    private javax.swing.JLabel tabPanelAgLblCostoCompra;
    private javax.swing.JLabel tabPanelAgLblEjCod;
    private javax.swing.JLabel tabPanelAgLblEjFecha;
    private javax.swing.JLabel tabPanelAgLblEjNoAlma;
    private javax.swing.JLabel tabPanelAgLblEjOfer;
    private javax.swing.JLabel tabPanelAgLblFechaVence;
    private javax.swing.JLabel tabPanelAgLblNoAlma;
    private javax.swing.JLabel tabPanelAgLblNomb;
    private javax.swing.JLabel tabPanelAgLblTempMax;
    private javax.swing.JLabel tabPanelAgLblTempMin;
    private javax.swing.JLabel tabPanelAgLblTiemAbr;
    private javax.swing.JLabel tabPanelAgLblTiemNoRefri;
    private javax.swing.JLabel tabPanelAgLblUnidDispo;
    private javax.swing.JLabel tabPanelAgLblUnidVend;
    private javax.swing.JRadioButton tabPanelAgRadBtnCadeFrio;
    private javax.swing.JToggleButton tabPanelAgTogBtnAggOfer;
    private javax.swing.JTextField tabPanelAgTxtCod;
    private javax.swing.JTextField tabPanelAgTxtCostoCompra;
    private javax.swing.JTextField tabPanelAgTxtFechaVence;
    private javax.swing.JTextField tabPanelAgTxtNoAlma;
    private javax.swing.JTextField tabPanelAgTxtNomb;
    private javax.swing.JTextField tabPanelAgTxtOfer;
    private javax.swing.JTextField tabPanelAgTxtTempMax;
    private javax.swing.JTextField tabPanelAgTxtTempMin;
    private javax.swing.JTextField tabPanelAgTxtTiemAbr;
    private javax.swing.JTextField tabPanelAgTxtTiemNoRefri;
    private javax.swing.JTextField tabPanelAgTxtUnidDispo;
    private javax.swing.JTextField tabPanelAgTxtUnidVend;
    private javax.swing.JPanel tabPanelModif;
    private javax.swing.JButton tabPanelModifBtnBorrar;
    private javax.swing.JButton tabPanelModifBtnElim;
    private javax.swing.JButton tabPanelModifBtnModif;
    private javax.swing.JButton tabPanelModifBtnRealizarCambios;
    private javax.swing.JComboBox<String> tabPanelModifCmbVig;
    private javax.swing.JLabel tabPanelModifLblCelsius1;
    private javax.swing.JLabel tabPanelModifLblCelsius2;
    private javax.swing.JLabel tabPanelModifLblCod;
    private javax.swing.JLabel tabPanelModifLblCostoCompra;
    private javax.swing.JLabel tabPanelModifLblEjCod;
    private javax.swing.JLabel tabPanelModifLblEjFecha;
    private javax.swing.JLabel tabPanelModifLblEjNoAlma;
    private javax.swing.JLabel tabPanelModifLblEjOfer;
    private javax.swing.JLabel tabPanelModifLblFechaVence;
    private javax.swing.JLabel tabPanelModifLblNoAlma;
    private javax.swing.JLabel tabPanelModifLblNomb;
    private javax.swing.JLabel tabPanelModifLblTempMax;
    private javax.swing.JLabel tabPanelModifLblTempMin;
    private javax.swing.JLabel tabPanelModifLblTiemAbr;
    private javax.swing.JLabel tabPanelModifLblTiemNoRefri;
    private javax.swing.JLabel tabPanelModifLblUnidDispo;
    private javax.swing.JLabel tabPanelModifLblUnidVend;
    private javax.swing.JRadioButton tabPanelModifRadBtnCadeFrio;
    private javax.swing.JToggleButton tabPanelModifTogBtnAggOfer;
    private javax.swing.JTextField tabPanelModifTxtCod;
    private javax.swing.JTextField tabPanelModifTxtCostoCompra;
    private javax.swing.JTextField tabPanelModifTxtFechaVence;
    private javax.swing.JTextField tabPanelModifTxtNoAlma;
    private javax.swing.JTextField tabPanelModifTxtNomb;
    private javax.swing.JTextField tabPanelModifTxtOfer;
    private javax.swing.JTextField tabPanelModifTxtTempMax;
    private javax.swing.JTextField tabPanelModifTxtTempMin;
    private javax.swing.JTextField tabPanelModifTxtTiemAbr;
    private javax.swing.JTextField tabPanelModifTxtTiemNoRefri;
    private javax.swing.JTextField tabPanelModifTxtUnidDispo;
    private javax.swing.JTextField tabPanelModifTxtUnidVend;
    // End of variables declaration//GEN-END:variables
}
